### PR TITLE
fix(dynamodb-enhanced): Fix NPE in EnhancedType for null and wildcard types

### LINKED ISSUE #5890: NPE when calling hashCode() on wildcard DynamoDB EnhancedType
### Describe the bug

When a DynamoDB EnhancedType is created for a wildcard type or a generic type having wildcard type parameters. Calling the hashCode() method on the EnhancedType results in a NullPointerException

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

The hashCode is computed successfully

### Current Behavior

`java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "this.rawClass" is null`

### Reproduction Steps

```
EnhancedType<Set<?>> enhancedType = new EnhancedType<Set<?>>(){};
int hashCode = enhancedType.hashCode();
```

### Possible Solution

Add a null check [here](https://github.com/aws/aws-sdk-java-v2/blob/9f735a10ba218860d15eeb4a8fcb6105ca04e92e/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/EnhancedType.java#L587)

### Additional Information/Context

_No response_

### AWS Java SDK version used

2.26.20

### JDK version used

openjdk version "17.0.12"

### Operating System and version

macOS Sonoma 14.5

### PR DESCRIPTION
**Pull request by abhu85**
## Summary

This PR fixes NullPointerException bugs in the DynamoDB Enhanced Client's `EnhancedType` class when dealing with wildcard types like `List<?>`.

**Issue #5890**: `EnhancedType.hashCode()`, `equals()`, and `toString()` throw NPE when dealing with wildcard types where `rawClass` is `null`.

## Root Cause

For wildcard types (e.g., `List<?>`), `EnhancedType` stores `rawClass = null`. The following methods called methods on `rawClass` without null checks:
- `hashCode()` called `rawClass.hashCode()`
- `equals()` called `rawClass.equals()`
- `innerToString()` called `rawClass.getTypeName()`

## Changes

- **EnhancedType.java**: Add null checks for `rawClass` in `hashCode()`, `equals()`, and `innerToString()` methods
- **EnhancedTypeTest.java**: Add 3 tests for wildcard type handling in `hashCode()`, `equals()`, and `toString()`

## Test Plan

- [x] All 26 `EnhancedTypeTest` tests pass (including 3 new tests)
- [x] Tests verify: wildcard hashCode, wildcard equality, wildcard toString

## Test Commands
\`\`\`bash
./mvnw test -pl services-custom/dynamodb-enhanced -Dtest=EnhancedTypeTest
# Tests run: 26, Failures: 0, Errors: 0, Skipped: 0
\`\`\`

Fixes #5890

---
*Note: The `ConverterUtils` fix for #6639 has been moved to a separate PR: #6761*

### CODE REVIEW

**Comment by bhoradc** [comment]
Hi @abhu85 

Thanks for the PR! If you don't mind, could you remove the `ConverterUtils` changes (#6639) from this PR and submit those as a separate PR? 

Also on the EnhancedType wildcard issue, we noticed that `toString()` has the same NPE when processing wildcard type parameters. Would you mind including a fix for that as well in this PR?

Thanks again for the contribution!

Regards, 
Chaitanya

**Comment by abhu85** [comment]
Hi @bhoradc,

Thanks for the feedback! I've addressed both requests:

1. **Split the PR**: Removed the `ConverterUtils` changes from this PR and submitted them separately as #6761.

2. **Added `toString()` fix**: Added null check in `innerToString()` for wildcard types, plus a test that verifies:
   - `wildcardParam.toString()` returns `"EnhancedType(?)"`  
   - `listWithWildcard.toString()` returns `"EnhancedType(java.util.List<?>)"`

**Summary of changes in this PR now:**
- `EnhancedType.java`: Null checks in `hashCode()`, `equals()`, and `toString()`/`innerToString()` for wildcard types
- `EnhancedTypeTest.java`: 3 tests for wildcard handling (hashCode, equals, toString)
- Updated changelog to reflect EnhancedType-only changes

Please let me know if any further changes are needed!

**Comment by bhoradc** [comment]
@abhu85 - Thanks for the quick updates. 

One more thing - could you update the PR description to reflect the current scope? It still references the `ConverterUtils` changes in all sections. Just to keep it clean and ensure we don't accidently close that issue once this merges. Thanks.

**Comment by abhu85** [comment]
Hi @bhoradc,

Apologies for the delay! I've updated the PR description to reflect the current scope - it now only references the `EnhancedType` changes for #5890. 

The `ConverterUtils` changes for #6639 remain in the separate PR #6761.

Please let me know if there's anything else needed!

File: services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/EnhancedTypeTest.java [hunk 1]
```diff
@@ -239,6 +239,45 @@ public void documentOf_withEnhancedTypeConfiguration() {
...
+        // with rawClass = null. hashCode() should handle this without NPE.
+        EnhancedType<List<?>> listWithWildcard = new EnhancedType<List<?>>(){};
+        EnhancedType<?> wildcardParam = listWithWildcard.rawClassParameters().get(0);
+
+        // This should not throw NPE
+        assertThatCode(() -> wildcardParam.hashCode()).doesNotThrowAnyException();
+    }
+
+    @Test
+    public void wildcardType_equals_handlesNullRawClass() {
```
Comment (alextwoods) [inline services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/EnhancedTypeTest.java:254]: We should add a testCase for wildCard != non wild card to more fully cover the ternary in the if

**Comment by abhu85** [comment]
Thanks for the feedback @alextwoods! I've added a test case `wildcardType_equals_notEqualToNonWildcard` that covers the wildcard != non-wildcard comparison, testing both directions:

```java
@Test
public void wildcardType_equals_notEqualToNonWildcard() {
    // A wildcard type (rawClass=null) should not be equal to a non-wildcard type (rawClass!=null)
    EnhancedType<List<?>> listWithWildcard = new EnhancedType<List<?>>(){};
    EnhancedType<?> wildcardType = listWithWildcard.rawClassParameters().get(0);
    EnhancedType<String> nonWildcardType = EnhancedType.of(String.class);

    // Wildcard vs non-wildcard should not be equal (tests both comparison directions)
    assertThat(wildcardType).isNotEqualTo(nonWildcardType);
    assertThat(nonWildcardType).isNotEqualTo(wildcardType);
}
```

This exercises the ternary logic in `equals()` line 572 when `this.rawClass == null` but `other.rawClass != null`, and vice versa.

**Comment by abhu85** [comment]
@alextwoods The CI is failing on the API surface area check because this PR modifies public methods in `EnhancedType.java` (`equals()`, `hashCode()`, `toString()`).

Could you please add one of the following labels after review?
- `api-surface-area-reviewed` - if the API changes are approved
- `no-api-surface-area-change` - if this is considered a false positive (the behavioral contract is unchanged, just null-safety improvements)

Thanks!

**Comment by alextwoods** [comment]
@abhu85  - Added the `no-api-surface-area-change` label since this doesn't have API changes. CI looks good other than that.
