### PR TITLE
Fixed an issue in InputStreamSubscriber that could cause NPE to be thrown when close and o…

### LINKED ISSUE #4081: NPE in software.amazon.awssdk.utils.async.InputStreamSubscriber
### Describe the bug

Occasionally seeing the following when downloading from S3
```
java.lang.NullPointerException
	at software.amazon.awssdk.utils.async.InputStreamSubscriber.close(InputStreamSubscriber.java:123)
	at software.amazon.awssdk.core.io.SdkFilterInputStream.close(SdkFilterInputStream.java:83)
```

### Expected Behavior

`InputStreamSubscriber.close` should not raise a NPE.

### Current Behavior

`java.lang.NullPointerException` is being thrown occasionally when closing inout stream.

### Reproduction Steps

It is hard to repro, as this only happens occasionally.

### Possible Solution

I think there might be a race condition causing a variable to be used before it is initialised. Adding a snapshot of the relevant code from [InputStreamSubscriber](https://github.com/aws/aws-sdk-java-v2/blob/2.20.59/utils/src/main/java/software/amazon/awssdk/utils/async/InputStreamSubscriber.java) below:
```java
 38 public final class InputStreamSubscriber extends InputStream implements Subscriber<ByteBuffer>, SdkAutoCloseable {
...
 44     private final AtomicReference<State> inputStreamState = new AtomicReference<>(State.UNINITIALIZED);
...
 48     private Subscription subscription;
...
 57     public void onSubscribe(Subscription s) {
 58         if (!inputStreamState.compareAndSet(State.UNINITIALIZED, State.READABLE)) {
 59             close();
 60             return;
 61         }
 62
 63         this.subscription = new CancelWatcher(s);
 64         delegate.onSubscribe(subscription);
 65     }
...
118     public void close() {
119         if (inputStreamState.compareAndSet(State.UNINITIALIZED, State.CLOSED)) {
120             delegate.onSubscribe(new NoOpSubscription());
121             delegate.onError(new CancellationException());
122         } else if (inputStreamState.compareAndSet(State.READABLE, State.CLOSED)) {
123             subscription.cancel();
124             onError(new CancellationException());
125         }
126     }
```
Considering the case where two threads access the class, one invoking the `onSubscribe` and the other `close`, it seems a race condition might cause the NPE when
  - `Thread1` invokes `onSubscribe` and executes the first statement (line 58), setting the state to `READABLE`
  - `Thread2` invokes `close` after `Thread1` executed line 58, but before it gets to execute line 63
      - Since the state is now `READABLE`, `Thread2` attempts to call `subscribe.cancel()` on an unitialised `subcriber`.

### Additional Information/Context

_No response_

### AWS Java SDK version used

2.20.59

### JDK version used

11

### Operating System and version

MacOS 13

### PR DESCRIPTION
**Pull request by zoewangg**
…nSubscribed get invoked concurrently.

## Motivation and Context
Fix #4081 The root cause is a race condition that onSubscribe and close are invoked concurrently, the subscription could be null, causing NPE to be thrown from close method.

## Modifications
Add a lock in onSubscribe and close

## Testing
Tested it locally and verified the test no longer failed with this change. This test is not checked in because it cannot reproduce this issue reliably. 
```
    @Test
    public void closeOnSubscribe_invokeAtSameTime_shouldNotFail() {
        int count = 0;
        for (int i = 0; i < 10000; i++) {
            CompletableFuture<Void> future = CompletableFuture.runAsync(() -> subscriber.close());
            //publisher.subscribe(subscriber);
            subscriber.onSubscribe(new Subscription() {
                @Override
                public void request(long n) {

                }

                @Override
                public void cancel() {

                }
            });
            future.join();
        }

    }
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] I have added a changelog entry. Adding a new entry must be accomplished by running the `scripts/new-change` script and following the instructions. Commit the new file created by the script in `.changes/next-release` with your changes.
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

File: utils/src/main/java/software/amazon/awssdk/utils/async/InputStreamSubscriber.java [hunk 1]
```diff
@@ -120,12 +124,14 @@ public int read(byte[] bytes, int off, int len) {
...
-            delegate.onError(new CancellationException());
-        } else if (inputStreamState.compareAndSet(State.READABLE, State.CLOSED)) {
-            subscription.cancel();
-            onError(new CancellationException());
+        synchronized (subscribeLock) {
+            if (inputStreamState.compareAndSet(State.UNINITIALIZED, State.CLOSED)) {
+                delegate.onSubscribe(new NoOpSubscription());
+                delegate.onError(new CancellationException());
+            } else if (inputStreamState.compareAndSet(State.READABLE, State.CLOSED)) {
+                subscription.cancel();
```
Comment (L-Applin) [inline utils/src/main/java/software/amazon/awssdk/utils/async/InputStreamSubscriber.java:132]: If `close()` is called before `onSubscribe(Subscription s)` it seems that the NPE would still occurs, should that be a concern?

Comment (zoewangg) [reply utils/src/main/java/software/amazon/awssdk/utils/async/InputStreamSubscriber.java:132]: I don't think it would since inputStreamState is UNINITIALIZED and it will execute the first if block

**Review by L-Applin — APPROVED** [review]
