### PR TITLE
Fix default user agent to comply with RFC 7231

### LINKED ISSUE #80: default user agent is illegal
The default user-agent format will reader `aws-sdk-java/2.0.0-preview-1 Linux/4.9.37-1-lts Java_HotSpot(TM)_64-Bit_Server_VM/25.131-b11/1.8.0_131 scala/2.12.2` on my machine. According to [rfc 7231](https://tools.ietf.org/html/rfc7231#section-5.5.3) this is illegal. The part `Java_HotSpot(TM)_64-Bit_Server_VM/25.131-b11/1.8.0_131` contrains two versions and the product name contains `()`.

Background: I'm implementing a async http client using akka-http, which [implement parsers](https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/scala/akka/http/impl/model/parser/CommonRules.scala#L381-L383) according to the RFCs. This might not be an issue in the past but since using a different http client is a feature now, everything being passed to/from the http client should be rfc compliant.

### PR DESCRIPTION
**Pull request by zoewangg**
## Description
Update default user agent to comply with [RFC 7231](https://tools.ietf.org/html/rfc7231#section-5.5.3)
after the change, user-agent would be something like this
 `aws-sdk-java/2.0.0-preview-9-SNAPSHOT Mac_OS_X/10.11.6 Java_HotSpot_TM__64-Bit_Server_VM/25.151-b12 Java/1.8.0_151`
fix #80 

## Testing
`mvn clean install`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [x] I have updated the Javadoc documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] A short description of the change has been added to the **CHANGELOG**

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

File: core/src/main/java/software/amazon/awssdk/core/util/UserAgentUtils.java [hunk 1]
```diff
@@ -73,33 +73,33 @@ static String userAgent() {
...
-     * Replace any spaces in the input with underscores.
+     * Replace any spaces, parentheses in the input with underscores.
      *
      * @param input the input
      * @return the input with spaces replaced by underscores
      */
-    private static String replaceSpaces(final String input) {
-        return input == null ? UNKNOWN : input.replace(' ', '_');
+    private static String sanitizeInput(String input) {
+        return input == null ? UNKNOWN : input.replaceAll("[() ]", "_");
```
Comment (millems) [inline core/src/main/java/software/amazon/awssdk/core/util/UserAgentUtils.java]: Should we use a whitelist instead of a blacklist? https://tools.ietf.org/html/rfc7230#section-3.2.6

File: core/src/main/java/software/amazon/awssdk/core/util/UserAgentUtils.java [hunk 2]
```diff
@@ -29,8 +29,8 @@
 @ThreadSafe
 public final class UserAgentUtils {
 
-    private static final String UA_STRING = "aws-sdk-{platform}/{version} {os.name}/{os.version} {java.vm.name}/{java.vm.version}"
-                                            + "/{java.version}{language.and.region}{additional.languages}";
+    private static final String UA_STRING = "aws-sdk-{platform}/{version} {os.name}/{os.version} {java.vm.name}/{java.vm"
+                                            + ".version} Java/{java.version}{language.and.region}{additional.languages}";
```
Comment (millems) [inline core/src/main/java/software/amazon/awssdk/core/util/UserAgentUtils.java]: I like it, but we should check to make sure this won't cause any metrics issues.

Comment (zoewangg) [reply core/src/main/java/software/amazon/awssdk/core/util/UserAgentUtils.java]: good point, will check with them.

File: core/src/main/java/software/amazon/awssdk/core/util/UserAgentUtils.java (hunk 1 above)
Comment (zoewangg) [reply core/src/main/java/software/amazon/awssdk/core/util/UserAgentUtils.java]: the whitelist seems to be very long and I don't think jvm, os name and versions are likely to have non-ascii characters. But I'll definitely add the rest of the disallowed characters:`"(),/:;<=>?@[\]{}`

File: core/src/main/java/software/amazon/awssdk/core/util/UserAgentUtils.java (hunk 2 above)
Comment (davidweinfls) [reply core/src/main/java/software/amazon/awssdk/core/util/UserAgentUtils.java]: Changes look good to me.
