### PR TITLE
Signal exceptions through CompletableFuture

### LINKED ISSUE #436: Investigate exception behavior in async client
Ensure we are only notifying failure through the CompletableFuture returned to the customer, I believe there may be cases where we throw an exception if it happens at a certain stage (i.e. marshalling). Having two delivery methods for exceptions is confusing and error prone.

### PR DESCRIPTION
**Pull request by dagnir**
Upon calling BaseAsyncClientHandler#execute, any exceptions that get
thrown over the lifetime of the request are signaled through to
CompletableFuture returned to the caller.

Fixes #436

## Motivation and Context
So that users only need to worry about one mechanism for dealing with exceptions on async requests instead of 2.

## Testing
`mvn clean install` with new unit tests.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [ ] A short description of the change has been added to the **CHANGELOG**

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

File: core/src/main/java/software/amazon/awssdk/core/util/CompletableFutures.java [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+ */
+
+package software.amazon.awssdk.core.util;
+
+import java.util.concurrent.CompletableFuture;
+
+/**
+ * Utility class for working with {@link CompletableFuture}.
+ */
+public final class CompletableFutures {
```
Comment (zoewangg) [inline core/src/main/java/software/amazon/awssdk/core/util/CompletableFutures.java]: I thought we have a checkstyle rule to validate against plural name.

File: core/src/test/java/software/amazon/awssdk/core/client/AsyncClientHandlerInterceptorExceptionTest.java [hunk 2]
```diff
@@ -0,0 +1,267 @@
...
+import utils.HttpTestUtils;
+
+/**
+ * Tests to ensure that any failures thrown from calling into the {@link
+ * software.amazon.awssdk.core.interceptor.ExecutionInterceptor}s is reported
+ * through the returned {@link java.util.concurrent.CompletableFuture}.
+ */
+@RunWith(Parameterized.class)
+public class AsyncClientHandlerInterceptorExceptionTest {
+    public enum Hook {
```
Comment (zoewangg) [inline core/src/test/java/software/amazon/awssdk/core/client/AsyncClientHandlerInterceptorExceptionTest.java]: minor, can we move this enum out side of this class, it's a bit huge now and we might add more tests in the future.

File: core/src/main/java/software/amazon/awssdk/core/util/CompletableFutures.java [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+     * <p />
+     * Similar to {@code CompletableFuture#failedFuture} which was added in
+     * Java 9.
+     *
+     * @param t The failure.
+     * @param <U> The type of the element.
+     * @return The failed future.
+     */
+    public static <U> CompletableFuture<U> failedFuture(Throwable t) {
+        CompletableFuture<U> cf = new CompletableFuture<>();
```
Comment (shorea) [inline core/src/main/java/software/amazon/awssdk/core/util/CompletableFutures.java]: Damn java for not have a static factory method to create an already failed future...

File: core/src/main/java/software/amazon/awssdk/core/util/CompletableFutures.java (hunk 1 above)
Comment (dagnir) [reply core/src/main/java/software/amazon/awssdk/core/util/CompletableFutures.java]: I believe that only applies to enums and enum-like classes.

cc: @millems

File: core/src/main/java/software/amazon/awssdk/core/client/BaseAsyncClientHandler.java [hunk 4]
```diff
@@ -85,32 +86,36 @@ protected BaseAsyncClientHandler(SdkClientConfiguration clientConfiguration,
         ExecutionContext executionContext,
         ResponseHandlerFactory<ReturnT> sdkHttpResponseHandlerFactory) {
 
-        InputT inputT = finalizeSdkRequest(executionContext);
+        try {
```
Comment (shorea) [inline core/src/main/java/software/amazon/awssdk/core/client/BaseAsyncClientHandler.java]: A client method looks like this typically.

```java
        HttpResponseHandler<BatchGetItemResponse> responseHandler = protocolFactory.createResponseHandler(
                new JsonOperationMetadata().withPayloadJson(true).withHasStreamingSuccessResponse(false),
                new BatchGetItemResponseUnmarshaller());

        HttpResponseHandler<AwsServiceException> errorResponseHandler = createErrorResponseHandler();

        return clientHandler.execute(new ClientExecutionParams<BatchGetItemRequest, BatchGetItemResponse>()
                .withMarshaller(new BatchGetItemRequestMarshaller(protocolFactory)).withResponseHandler(responseHandler)
                .withErrorResponseHandler(errorResponseHandler).withInput(batchGetItemRequest));
```

Are we sure nothing but the client handler could ever throw an exception?

File: core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncExecutionFailureExceptionReportingStage.java [hunk 5]
```diff
@@ -33,12 +34,15 @@ public AsyncExecutionFailureExceptionReportingStage(RequestPipeline<SdkHttpFullR
 
     @Override
     public CompletableFuture<OutputT> execute(SdkHttpFullRequest input, RequestExecutionContext context) throws Exception {
-        return wrapped.execute(input, context).whenComplete((o, t) -> {
+        return wrapped.execute(input, context).handle((o, t) -> {
             if (t != null) {
                 Context.FailedExecution failedContext =
                         new DefaultFailedExecutionContext(context.executionContext().interceptorContext(), t);
+                //TODO: To obtrude or not to obtrude?
```
Comment (shorea) [inline core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncExecutionFailureExceptionReportingStage.java]: What does obtrude mean?

Comment (dagnir) [reply core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncExecutionFailureExceptionReportingStage.java]: With this change, since this method gets called when an exception happens further up the pipeline, if the interceptor also throws, then we throw that exception instead of the original exception. Not sure what behavior we want

File: core/src/main/java/software/amazon/awssdk/core/client/BaseAsyncClientHandler.java (hunk 4 above)
Comment (dagnir) [reply core/src/main/java/software/amazon/awssdk/core/client/BaseAsyncClientHandler.java]: Hmm good point. I guess it wouldn't hurt to wrap the entire operation method in a try-catch as well.

File: core/src/main/java/software/amazon/awssdk/core/util/CompletableFutures.java (hunk 3 above)
Comment (dagnir) [reply core/src/main/java/software/amazon/awssdk/core/util/CompletableFutures.java]: Lol I'm guessing it was an oversight since `CompletableFuture#completedFuture` exists in 8.

File: core/src/test/java/software/amazon/awssdk/core/client/AsyncClientHandlerInterceptorExceptionTest.java (hunk 2 above)
Comment (dagnir) [reply core/src/test/java/software/amazon/awssdk/core/client/AsyncClientHandlerInterceptorExceptionTest.java]: My only concern is that it really doesn't make sense outside of this test class. Would moving it to the bottom so that you see the `@Test`s first work for you?

File: core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncExecutionFailureExceptionReportingStage.java (hunk 5 above)
Comment (shorea) [reply core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncExecutionFailureExceptionReportingStage.java]: Oh gotcha. I say we should favor the original exception if it's present.

File: core/src/main/java/software/amazon/awssdk/core/util/CompletableFutures.java (hunk 1 above)
Comment (millems) [reply core/src/main/java/software/amazon/awssdk/core/util/CompletableFutures.java]: Yes, the rule only applies to enums or classes with public static fields.

File: core/src/main/java/software/amazon/awssdk/core/util/CompletableFutures.java (hunk 3 above)
Comment (millems) [reply core/src/main/java/software/amazon/awssdk/core/util/CompletableFutures.java]: Added in Java 9: https://docs.oracle.com/javase/10/docs/api/java/util/concurrent/CompletableFuture.html#failedFuture(java.lang.Throwable)

File: core/src/main/java/software/amazon/awssdk/core/util/CompletableFutures.java (hunk 1 above)
Comment (dagnir) [reply core/src/main/java/software/amazon/awssdk/core/util/CompletableFutures.java]: Done

File: core/src/main/java/software/amazon/awssdk/core/client/BaseAsyncClientHandler.java (hunk 4 above)
Comment (dagnir) [reply core/src/main/java/software/amazon/awssdk/core/client/BaseAsyncClientHandler.java]: Now wrapping the body in a `try-catch`

File: core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncExecutionFailureExceptionReportingStage.java (hunk 5 above)
Comment (dagnir) [reply core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncExecutionFailureExceptionReportingStage.java]: Sounds good, preserving the original exception

File: core/src/test/java/software/amazon/awssdk/core/client/AsyncClientHandlerInterceptorExceptionTest.java (hunk 2 above)
Comment (dagnir) [reply core/src/test/java/software/amazon/awssdk/core/client/AsyncClientHandlerInterceptorExceptionTest.java]: Done!
