### PR TITLE
Fix NPE issue in multipart S3 client

### LINKED ISSUE #6464: NPE if s3AsyncClient.putObject is called with body containing empty content and unknown length
### Describe the bug

Excecuting main (see reproductions steps) results in ExecutionException with a NPE as cause.

main works if either 
- content contain at least one byte or
- content length inAsyncRequestBody.fromInputStream() is set to 0 (instead of unknown: null)

main does not work with content=""; and contentlength=null;

I used google storage, but I don't think that the issue is google specific 

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Main should put empty object without Exception

### Current Behavior

```.log
Exception is thrown:
Exception in thread "main" java.util.concurrent.ExecutionException: software.amazon.awssdk.core.exception.SdkClientException: Cannot invoke "software.amazon.awssdk.core.async.AsyncRequestBody.contentType()" because "this.asyncRequestBody" is null
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at com.opentext.ecm.ac.migration.server.ContentNPE.main(ContentNPE.java:58)
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Cannot invoke "software.amazon.awssdk.core.async.AsyncRequestBody.contentType()" because "this.asyncRequestBody" is null
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:130)
	at software.amazon.awssdk.core.internal.util.ThrowableUtils.asSdkException(ThrowableUtils.java:98)
	at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.doExecute(BaseAsyncClientHandler.java:248)
	at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.lambda$execute$1(BaseAsyncClientHandler.java:80)
	at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.measureApiCallSuccess(BaseAsyncClientHandler.java:294)
	at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.execute(BaseAsyncClientHandler.java:73)
	at software.amazon.awssdk.awscore.client.handler.AwsAsyncClientHandler.execute(AwsAsyncClientHandler.java:49)
	at software.amazon.awssdk.services.s3.DefaultS3AsyncClient.putObject(DefaultS3AsyncClient.java:12982)
	at software.amazon.awssdk.services.s3.DelegatingS3AsyncClient.lambda$putObject$89(DelegatingS3AsyncClient.java:10008)
	at software.amazon.awssdk.services.s3.internal.multipart.MultipartS3AsyncClient$1.invokeOperation(MultipartS3AsyncClient.java:108)
	at software.amazon.awssdk.services.s3.DelegatingS3AsyncClient.putObject(DelegatingS3AsyncClient.java:10008)
	at software.amazon.awssdk.services.s3.internal.multipart.MultipartUploadHelper.uploadInOneChunk(MultipartUploadHelper.java:155)
	at software.amazon.awssdk.services.s3.internal.multipart.UploadWithUnknownContentLengthHelper$UnknownContentLengthAsyncRequestBodySubscriber.onComplete(UploadWithUnknownContentLengthHelper.java:282)
	at software.amazon.awssdk.utils.async.SimplePublisher.doProcessQueue(SimplePublisher.java:275)
	at software.amazon.awssdk.utils.async.SimplePublisher.processEventQueue(SimplePublisher.java:224)
	at software.amazon.awssdk.utils.async.SimplePublisher.complete(SimplePublisher.java:157)
	at software.amazon.awssdk.core.internal.async.SplittingPublisher$SplittingSubscriber.onComplete(SplittingPublisher.java:247)
	at software.amazon.awssdk.utils.async.SimplePublisher.doProcessQueue(SimplePublisher.java:275)
	at software.amazon.awssdk.utils.async.SimplePublisher.processEventQueue(SimplePublisher.java:224)
	at software.amazon.awssdk.utils.async.SimplePublisher.complete(SimplePublisher.java:157)
	at software.amazon.awssdk.utils.async.InputStreamConsumingPublisher.doBlockingWrite(InputStreamConsumingPublisher.java:62)
	at software.amazon.awssdk.core.async.BlockingInputStreamAsyncRequestBody.writeInputStream(BlockingInputStreamAsyncRequestBody.java:95)
	at software.amazon.awssdk.core.internal.async.InputStreamWithExecutorAsyncRequestBody.doBlockingWrite(InputStreamWithExecutorAsyncRequestBody.java:112)
	at software.amazon.awssdk.core.internal.async.InputStreamWithExecutorAsyncRequestBody.lambda$subscribe$0(InputStreamWithExecutorAsyncRequestBody.java:80)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "software.amazon.awssdk.core.async.AsyncRequestBody.contentType()" because "this.asyncRequestBody" is null
	at software.amazon.awssdk.core.runtime.transform.AsyncStreamingRequestMarshaller.marshall(AsyncStreamingRequestMarshaller.java:50)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$finalizeSdkHttpFullRequest$0(BaseClientHandler.java:73)
	at software.amazon.awssdk.core.internal.util.MetricUtils.measureDuration(MetricUtils.java:64)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.finalizeSdkHttpFullRequest(BaseClientHandler.java:72)
	at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.doExecute(BaseAsyncClientHandler.java:199)
	... 26 more
```

### Reproduction Steps

```.java
public static void main(String[] args) throws ExecutionException, InterruptedException {

        String bucket                   = "<your bucket>";
        URI endpointOverride            = URI.create( "https://storage.googleapis.com/"); // same result for AWS
        String region                   = "<your region>";
        AwsBasicCredentials credentials = AwsBasicCredentials.create( "<your access key>"
                                                                    ,"<your secret>" );

        // "" throws ExecutionException with NPE. Works if not empty e.g. "a"
        String content="";
        InputStream inStream = new ByteArrayInputStream(content.getBytes(StandardCharsets.UTF_8));

        S3AsyncClient s3AsyncClient = S3AsyncClient.builder()
                .credentialsProvider( StaticCredentialsProvider.create( credentials ) )
                .endpointOverride( endpointOverride )
                .forcePathStyle( Boolean.TRUE )
                .multipartEnabled(true)
                .httpClientBuilder( NettyNioAsyncHttpClient.builder() )
                .region( Region.of( region ) )
                .requestChecksumCalculation(RequestChecksumCalculation.WHEN_REQUIRED)     // needed for google
                .responseChecksumValidation(ResponseChecksumValidation.WHEN_REQUIRED)     // needed for google
                .build();

        ExecutorService executor = Executors.newSingleThreadExecutor();
        try {
            AsyncRequestBody body = AsyncRequestBody.fromInputStream(inStream, (Long) null /* contentLength unknown */, executor);
            CompletableFuture<PutObjectResponse> poFuture = s3AsyncClient.putObject(PutObjectRequest.builder()
                            .bucket(bucket)
                            .key( "testContent/empty.txt")
                            .build(),
                    body);

            PutObjectResponse poRes = poFuture.get(); // may throw InterruptedException or ExecutionException
            if (poRes == null || !poRes.sdkHttpResponse().isSuccessful()) {
                throw new ExecutionException(new IOException("Object upload failed"));
            }
            System.out.println("Success for content=\"" + content + "\"");
        } finally {
            executor.shutdownNow();
        }
    }
```

### Possible Solution

_No response_

### Additional Information/Context

Workaround:
I use a BufferedInputStream to detect, if inStream is empty or not. If empty I set contentlength=0 in AsyncRequestBody.fromInputStream(). If not empty, I usecontentlength=null

### AWS Java SDK version used

2.34.5

### JDK version used

openjdk17.0.15

### Operating System and version

windows 11

### PR DESCRIPTION
**Pull request by zoewangg**
## Motivation and Context
Fix NPE issue thrown when using multipart S3 client to upload an object containing empty content without supplying a content length. Fix #6464

When uploading an empty object with unknown content length using the S3 multipart client, a NullPointerException was thrown because the code didn't handle the case
where no async request body chunks are received before the stream completes.

## Modifications
• Modified UploadWithUnknownContentLengthHelper to handle empty streams by checking if any async request body has been received before onComplete() is called
• Added null check in onNext() to fail gracefully if a null async request body is passed
• Renamed isFirstAsyncRequestBody to firstAsyncRequestBodyReceived for better clarity
• When no request body is received, use AsyncRequestBody.empty() for single object upload

## Testing
• Added new tests

## Types of changes
• [x] Bug fix (non-breaking change which fixes an issue)
• [ ] New feature (non-breaking change which adds functionality)

## Checklist
• [x] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
• [x] Local run of mvn install succeeds
• [x] My code follows the code style of this project
• [ ] My change requires a change to the Javadoc documentation
• [ ] I have updated the Javadoc documentation accordingly
• [x] I have added tests to cover my changes
• [x] All new and existing tests passed
• [x] I have added a changelog entry. Adding a new entry must be accomplished by running the scripts/new-change script and following the instructions. Commit the new
file created by the script in .changes/next-release with your changes.
• [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License
• [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

File: services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/utils/MultipartUploadTestUtils.java [hunk 1]
```diff
@@ -69,6 +71,23 @@ public static void stubSuccessfulCompleteMultipartCall(String bucket, String key
...
+    public static void stubSuccessfulPutObjectCall(S3AsyncClient s3AsyncClient) {
+        when(s3AsyncClient.putObject(any(PutObjectRequest.class), any(AsyncRequestBody.class)))
+            .thenAnswer(new Answer<CompletableFuture<PutObjectResponse>>() {
+
+                @Override
+                public CompletableFuture<PutObjectResponse> answer(InvocationOnMock invocationOnMock) {
+                    AsyncRequestBody AsyncRequestBody = invocationOnMock.getArgument(1);
+                    // Draining the request body
+                    AsyncRequestBody.subscribe(b -> {
+                    });
```
Comment (zoewangg) [inline services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/utils/MultipartUploadTestUtils.java]:
```suggestion
                    AsyncRequestBody asyncRequestBody = invocationOnMock.getArgument(1);
                    // Draining the request body
                    asyncRequestBody.subscribe(b -> {
                    });
```

**Review by L-Applin — APPROVED** [review]

File: services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/UploadWithUnknownContentLengthHelper.java [hunk 2]
```diff
@@ -163,9 +163,17 @@ public void onSubscribe(Subscription s) {
 
         @Override
         public void onNext(CloseableAsyncRequestBody asyncRequestBody) {
+            if (asyncRequestBody == null) {
```
Comment (RanVaknin) [inline services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/UploadWithUnknownContentLengthHelper.java:166]: Do we need to add `isDone = true` here just like with `onError()` ?

File: services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/UploadWithUnknownContentLengthHelper.java [hunk 3]
```diff
@@ -163,9 +163,17 @@ public void onSubscribe(Subscription s) {
...
+                NullPointerException exception = new NullPointerException("asyncRequestBody passed to onNext MUST NOT be null.");
+                multipartUploadHelper.failRequestsElegantly(futures,
```
Comment (RanVaknin) [inline services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/UploadWithUnknownContentLengthHelper.java:168]: Noob question, I assume there is a reason we use `failRequestsElegantly` here. The Reactive Streams [spec](https://github.com/reactive-streams/reactive-streams-jvm#user-content-2.13) requires throwing NPE when onNext() receives null. Is there a reason we complete the future exceptionally but don't throw to the caller?

Comment (zoewangg) [reply services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/UploadWithUnknownContentLengthHelper.java:168]: Good call, we should throw in the end to be compliant to the spec. To answer your question, we need to complete the future exceptionally (by calling failRequestElegantly) here because something else is depending on the completion of the future.

File: services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/UploadWithUnknownContentLengthHelper.java (hunk 2 above)
Comment (zoewangg) [reply services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/UploadWithUnknownContentLengthHelper.java:166]: Do you mean moving `isDone` check before this? Probably not, since we want to always error out if the item received is null

Comment (RanVaknin) [reply services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/UploadWithUnknownContentLengthHelper.java:166]: No I meant setting `isDone = true` in case the request body is null: 

```diff
        @Override
        public void onNext(CloseableAsyncRequestBody asyncRequestBody) {
            if (asyncRequestBody == null) {
                NullPointerException exception = new NullPointerException("asyncRequestBody passed to onNext MUST NOT be null.");
+              isDone = true;
                multipartUploadHelper.failRequestsElegantly(futures,
                                                            exception, uploadId, returnFuture, putObjectRequest);
                throw exception;
            }
```

onError() [does the same thing](https://github.com/aws/aws-sdk-java-v2/blob/1b1e3b4b51b5d9d1201a74264f1b5367280cbadd/services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/UploadWithUnknownContentLengthHelper.java#L279):

```java
        @Override
        public void onError(Throwable t) {
            log.debug(() -> "Received onError() ", t);
            if (failureActionInitiated.compareAndSet(false, true)) {
                isDone = true;
                multipartUploadHelper.failRequestsElegantly(futures, t, uploadId, returnFuture, putObjectRequest);
            }
        }
```

In my mind this makes sense because we are marking the end of the subscription in the case that the publisher misbehaves and sends null. I guess its not as necessary since we now surface an exception?

Comment (zoewangg) [reply services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/UploadWithUnknownContentLengthHelper.java:166]: Yeah, it's not necessary since we will throw exception now
