### PR TITLE
Properly set content-type for RPCv2 event streams

### LINKED ISSUE #5894: Wrong `:content-type` header is set on RPCv2 CBOR event stream initial-request events
### Describe the bug

The SDK [uses the request's content-type header to set the initial-request's `:content-type` header](https://github.com/aws/aws-sdk-java-v2/blob/9fa37f9d4a057291d830654f94609ec291130058/core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamInitialRequestInterceptor.java#L74-L76). [AWS/JSON has the base request's content-type set to the correct value](https://github.com/aws/aws-sdk-java-v2/blob/9fa37f9d4a057291d830654f94609ec291130058/core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonProtocolMarshaller.java#L285) but [RPCv2 CBOR uses the event-stream mime type from the start](https://github.com/aws/aws-sdk-java-v2/blob/9fa37f9d4a057291d830654f94609ec291130058/core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonProtocolMarshaller.java#L287). This causes the initial request for an RPCv2 CBOR event stream to always have a content-type of `application/vnd.amazon.eventstream` instead of the type it's actually serialized as, `application/cbor`.

This code works as-is for rest-json because rest-json does not use an initial-request event.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

CBOR initial-event has `application/cbor` content type

### Current Behavior

CBOR initial-event has `application/vnd.amazon.eventstream` content type

### Reproduction Steps

Initiate an RPCv2 event streaming request and see the `:content-type` on the initial event

### Possible Solution

Move RPCv2 CBOR to https://github.com/aws/aws-sdk-java-v2/blob/9fa37f9d4a057291d830654f94609ec291130058/core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonProtocolMarshaller.java#L283

### Additional Information/Context

_No response_

### AWS Java SDK version used

n/a

### JDK version used

n/a

### Operating System and version

n/a

### PR DESCRIPTION
**Pull request by sugmanue**
## Motivation and Context

For RPCv2 we were unconditionally setting the `:content-type` header for each event to `application/vnd.amazon.eventstream` because we are first setting [that content-type on the request](https://github.com/aws/aws-sdk-java-v2/blob/6c74e87c0ef16472b33fb2dc33de6a18806dbe3a/core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamInitialRequestInterceptor.java#L56) then [using it in the request content-type in the event stream](https://github.com/aws/aws-sdk-java-v2/blob/6c74e87c0ef16472b33fb2dc33de6a18806dbe3a/core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamInitialRequestInterceptor.java#L81)

This change fixes this to properly use the given `:content-type`. Fixes #5894.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [ ] Local run of `mvn install` succeeds
- [ ] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed
- [ ] I have added a changelog entry. Adding a new entry must be accomplished by running the `scripts/new-change` script and following the instructions. Commit the new file created by the script in `.changes/next-release` with your changes.
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [ ] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Review by Fred1155 — APPROVED** [review]

File: core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonProtocolMarshaller.java [hunk 1]
```diff
@@ -280,10 +280,10 @@ private SdkHttpFullRequest finishMarshalling() {
         if (!request.firstMatchingHeader(CONTENT_TYPE).isPresent() && !hasEvent) {
             if (hasEventStreamingInput) {
                 AwsJsonProtocol protocol = protocolMetadata.protocol();
-                if (protocol == AwsJsonProtocol.AWS_JSON) {
+                if (protocol == AwsJsonProtocol.AWS_JSON || protocol == AwsJsonProtocol.SMITHY_RPC_V2_CBOR) {
                     // For RPC formats, this content type will later be pushed down into the `initial-event` in the body
```
Comment (Fred1155) [inline core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonProtocolMarshaller.java:284]: Do we need to change the comments?

File: core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonProtocolMarshaller.java [hunk 2]
```diff
@@ -280,10 +280,10 @@ private SdkHttpFullRequest finishMarshalling() {
         if (!request.firstMatchingHeader(CONTENT_TYPE).isPresent() && !hasEvent) {
             if (hasEventStreamingInput) {
                 AwsJsonProtocol protocol = protocolMetadata.protocol();
-                if (protocol == AwsJsonProtocol.AWS_JSON) {
+                if (protocol == AwsJsonProtocol.AWS_JSON || protocol == AwsJsonProtocol.SMITHY_RPC_V2_CBOR) {
```
[the remark this answers is not in the document]
Comment (zoewangg) [reply core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonProtocolMarshaller.java:283]: Discussed offline, can be addressed as a quick followup

File: core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonProtocolMarshaller.java (hunk 1 above)
Comment (sugmanue) [reply core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonProtocolMarshaller.java:284]: The comment was there long before, but yeah, if feels inaccurate. I will update it (or remove it) in a follow up.
