### PR TITLE
Fix #1035: Skip Etag validation for upload of KMS encrypted objects 

### LINKED ISSUE #1035: S3 ETag should not be validated if using KMS SSE
## Expected Behavior
[Version 1](https://github.com/aws/aws-sdk-java/blob/5fb7554098a60228347ab823ddde06567f1ef85c/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/SkipMd5CheckStrategy.java#L245) of the AWS SDK skipped the ETag validation check if KMS server side encryption is used. This is causing issues using LocalStack which is returning the ETag regardless. 

According to the [API](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html)

    In the response, Amazon S3 returns the encryption algorithm and MD5 of the encryption key that you specified when uploading the object. 
    The ETag that is returned is not the MD5 of the object.

## Current Behavior
`ChecksumsEnabledValidator` executes the Checksum check if a ETag is returned, causing a NPE ([as the request context doesn't include the checksum](https://github.com/aws/aws-sdk-java-v2/blob/a0379920f54cba715773f821ac5d237be8a47985/services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumsEnabledValidator.java#L104)).

  
    Caused by: java.lang.NullPointerException: null
    	at software.amazon.awssdk.services.s3.checksums.ChecksumsEnabledValidator.validatePutObjectChecksum(ChecksumsEnabledValidator.java:129)
    	at software.amazon.awssdk.services.s3.internal.handlers.AsyncChecksumValidationInterceptor.afterUnmarshalling(AsyncChecksumValidationInterceptor.java:86)

## Possible Solution
~~Check if the validation should be executed on the response in [ChecksumsEnabledValidator#validatePutObjectChecksum](https://github.com/aws/aws-sdk-java-v2/blob/a0379920f54cba715773f821ac5d237be8a47985/services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumsEnabledValidator.java#L128), similar to V1 or include a null check for `checksum`.~~

## Context
Bug raised with https://github.com/localstack/localstack/issues/1092 too.

## Your Environment
* AWS Java SDK version used: 2.3.6
* JDK version used: 1.8
* Operating System and version: Mac OS 10.13.6

### PR DESCRIPTION
**Pull request by kgncan**
## Description

The check in `putObjectChecksumEnabled` in [AsyncChecksumValidationInterceptor](https://github.com/aws/aws-sdk-java-v2/blob/a0379920f54cba715773f821ac5d237be8a47985/services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/AsyncChecksumValidationInterceptor.java#L82) should use request headers, rather than response headers, to determine if the put request is a SSE KMS request. 

## Motivation and Context

Fix for https://github.com/aws/aws-sdk-java-v2/issues/1035 

## Testing

Added unit tests for `afterUnmarshalling`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] A short description of the change has been added to the **CHANGELOG**
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](../docs/LaunchChangelog.md)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

File: services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/handlers/AsyncChecksumValidationInterceptorTest.java [hunk 1]
```diff
@@ -115,6 +121,82 @@ public void modifyAsyncHttpResponseContent_nonGetObjectRequest_shouldNotModify()
...
+
+        SdkHttpRequest sdkHttpRequest = SdkHttpFullRequest.builder()
+                                                          .uri(URI.create("http://localhost:8080"))
+                                                          .method(SdkHttpMethod.PUT)
+                                                          .build();
+
+        Context.AfterUnmarshalling afterUnmarshallingContext =
+            InterceptorTestUtils.afterUnmarshallingContext(putObjectRequest, sdkHttpRequest, response, sdkHttpResponse);
+
+        interceptor.afterUnmarshalling(afterUnmarshallingContext, executionAttributes);
```
Comment (zoewangg) [inline services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/handlers/AsyncChecksumValidationInterceptorTest.java]: Nit: can we use 
`assertThatThrownBy(()  -> nterceptor.afterUnmarshalling(afterUnmarshallingContext, executionAttributes)).hasMessageContaining("Data read has a different checksum than expected.")` instead of using `expected = SdkClientException.class`?

File: .changes/next-release/bugfix-AWSS3-3112634.json [hunk 2]
```diff
@@ -0,0 +1,5 @@
+{
+    "category": "AWS S3", 
+    "type": "bugfix", 
+    "description": "Skip Etag validation for KMS encrypted objects"
```
Comment (zoewangg) [inline .changes/next-release/bugfix-AWSS3-3112634.json]: minor, can we update the description to something like "Use request header to determine if  checksum validation should be enabled for `s3#putObject`"

File: services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/handlers/AsyncChecksumValidationInterceptorTest.java (hunk 1 above)
Comment (kgncan) [reply services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/handlers/AsyncChecksumValidationInterceptorTest.java]: 👍

File: services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/handlers/AsyncChecksumValidationInterceptorTest.java [hunk 3]
```diff
@@ -20,24 +20,30 @@
...
+import software.amazon.awssdk.http.SdkHttpFullRequest;
+import software.amazon.awssdk.http.SdkHttpMethod;
+import software.amazon.awssdk.http.SdkHttpRequest;
 import software.amazon.awssdk.http.SdkHttpResponse;
 import software.amazon.awssdk.services.s3.S3Configuration;
 import software.amazon.awssdk.services.s3.checksums.ChecksumCalculatingAsyncRequestBody;
 import software.amazon.awssdk.services.s3.checksums.ChecksumValidatingPublisher;
-import software.amazon.awssdk.services.s3.model.GetObjectRequest;
-import software.amazon.awssdk.services.s3.model.PutObjectRequest;
+import software.amazon.awssdk.services.s3.model.*;
```
[the remark this answers is not in the document]
Comment (kgncan) [reply services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/handlers/AsyncChecksumValidationInterceptorTest.java]: 👍
