### PR TITLE
Consider outstanding demand in ByteBufferStoringSubscriber before requesting more

### LINKED ISSUE #3726: S3 Transfer Manager upload causes memory issues
### Describe the bug

Trying to upload a large amount of file (~50GB in about 400 files) with the TransferManager uses a huge amount of memory. The JVM size (as reported by top) greatly exceeds the max heap size configured at startup (we start with -mx6G so we can stay below 16GB).

We tried adjusting the available configurations of both transfer manager and async S3 client, with no success; this involved a lot of trial and error because it was not clear how they interact exactly.
- the TransferManager can be given an Executor, but then seems to immediately empty the requests into the asyncronous client?
- we limited the S3Client's maxConcurrency, but this didn't have to have any influence
- we did not find any configuration for total or individual connections' buffer size

### Expected Behavior

The transfer manager could throttle requests towards the S3 client if too many failed requests occur, and/or the configuration should enable the configuration of a maximum total buffer.

### Current Behavior

This results in many of the uploads to fail in the best case, in application shutdown (by the OS because of host RAM exhaustion) in the worst.

If the uploads fail, a `CompletedDirectoryUpload` is returned, correctly containing the failed files, and the memory situation recovers.

Outputting the `CompletedDirectoryUpload.failedDownloads()` result looks like this:
```
[FailedFileUpload(request=UploadFileRequest(putObjectRequest=PutObjectRequest(Bucket=<our-bucket>, Key=<target-path>, source=<local_file>, configuration=[<our-logging-listener>]), exception=software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Java heap space), [...]]
```
The configured `TransferListener` logs success and failure; the failure case looks like
```
software.amazon.awssdk.core.exception.SdkClientException: Failed to send the request: A callback has reported failure.
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111)
	at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:43)
	at software.amazon.awssdk.services.s3.internal.crt.S3CrtResponseHandlerAdapter.handleError(S3CrtResponseHandlerAdapter.java:127)
	at software.amazon.awssdk.services.s3.internal.crt.S3CrtResponseHandlerAdapter.onFinished(S3CrtResponseHandlerAdapter.java:93)
	at software.amazon.awssdk.crt.s3.S3MetaRequestResponseHandlerNativeAdapter.onFinished(S3MetaRequestResponseHandlerNativeAdapter.java:24)
```

Our current workaround is to set the JVM memory low enough that the OS does not shut down the process, so we get returned the list as described; we can then retry single file which works fine.

### Reproduction Steps

This is our setup:
```
var tm = S3TransferManager.builder()
   .s3Client(S3AsyncClient.crtBuilder()
      .credentialsProvider(awsCredentialsProvider)
      .maxConcurrency(10)
      .targetThroughputInGbps(0.6d)
      .build())
   .build();
tm.uploadDirectory(builder -> builder
            .bucket(ourBucket)
            .source(Path.of(ourDirectory))
            .s3Prefix(s3DirectoryKey)
            .uploadFileRequestTransformer(transformer -> transformer.addTransferListener(loggingListener))
        )
}
```
The loggingListener really only logs success and failure:
```
class LoggingTransferListener implements TransferListener {
        @Override
        public void transferComplete(final Context.TransferComplete context) {
            logService.info(log, "transfer complete");
        }

        @Override
        public void transferFailed(final Context.TransferFailed context) {
            logService.error(log, "transfer failed", context.exception());
        }
}
```

We're assuming the main issue is the amount of data. 

### Possible Solution

- allow overall available memory configuration
- size the individual connections' buffer dynamically according to available or configured memory

### Additional Information/Context

Our use case is persisting a Kafka Streams state store, to give an idea of how the data to be stored is structured. Total size is about 20-25GB across ~400 files as mentioned in the bug description.

### AWS Java SDK version used

2.19.21

### JDK version used

17.0.6

### Operating System and version

Linux 4.14.301-224.520.amzn2.x86_64

### PR DESCRIPTION
**Pull request by alextwoods**
Considers the outstanding demand (in flight request to the subscription) in ByteBufferStoringSubscriber before requesting more.

## Motivation and Context
Fixes #3726

The ByteBufferStoringSubscriber requests more data from its subscription in two cases:
1. when data is read when `transferTo` is called.
2. when receiving data from `onNext`.

In both cases, it will only request more when the amount of buffered data is less than its limit.  However, it was not considering unfulfilled requests (ie, requests that have been made to the subscription, but which have not yet been fulfilled) - it is possible then for the ByteBufferStoringSubscriber to queue up a large number of requests and once those are finally fulfilled, end up with a large number of events that are buffered.  This can lead to OutOfMemory issues, in particularly when using a bursty Publisher/Subscription (ie, one that will fulfill a large number of requests quickly and then wait for awhile to build up more outstanding requests - an example of this is the [FileAsyncRequestBody](https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/FileAsyncRequestBody.java#L431))

## Modifications
* Sets a `byteBufferSizeHint` when `onNext` is called.
* Track outstanding demand (ie, the difference between requests and onNext calls).
* Don't make more requests if the estimated in flight requests + current buffer is larger than the `minimumBytesBuffered`
* Increases the `MINIMUM_BYTES_BUFFERED` back to 16 MB as it was before #3800 - the lower limit was required when outstanding demand wasn't considered.

A note on the use of `AtomicInteger` for tracking` outstandingDemand` vs `volatile long` for tracking `byteBufferSizeHint` - `outstandingDemand` is a counter and requires atomic updates (since we are incrementing/decrementing it).  `byteBufferSizeHint` on the other hand is simply set to whatever the latest size is.  It should be volatile so that whatever thread is accessing it gets the latest values, but its updates do not need to be atomic.

## Testing
Added new unit tests.  Manual testing with a large file upload and small max heap size - before the change, hit OOM, with the change, memory usage is much lower (200 mb -> 40 mb max usage for a 2 GB file).

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] I have added a changelog entry. Adding a new entry must be accomplished by running the `scripts/new-change` script and following the instructions. Commit the new file created by the script in `.changes/next-release` with your changes.
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

File: utils/src/main/java/software/amazon/awssdk/utils/async/ByteBufferStoringSubscriber.java [hunk 1]
```diff
@@ -56,6 +57,10 @@ public class ByteBufferStoringSubscriber implements Subscriber<ByteBuffer> {
 
     private final Phaser phaser = new Phaser(1);
 
+    private final AtomicInteger outstandingDemand = new AtomicInteger(0);
+
+    private final Optional<Integer> maximumOutstandingDemand;
```
Comment (zoewangg) [inline utils/src/main/java/software/amazon/awssdk/utils/async/ByteBufferStoringSubscriber.java]: minor: per our guideline, Optional SHOULD NOT be used for member variables

https://github.com/aws/aws-sdk-java-v2/blob/master/docs/guidelines/UseOfOptional.md

File: utils/src/main/java/software/amazon/awssdk/utils/async/ByteBufferStoringSubscriber.java [hunk 2]
```diff
@@ -204,7 +224,13 @@ private void addBufferedDataAmount(long amountToAdd) {
     }
 
     private void maybeRequestMore(long currentDataBuffered) {
+        // if we have too many outstanding requests, no need to make more requests
+        if (maximumOutstandingDemand.isPresent() && outstandingDemand.get() >= maximumOutstandingDemand.get()) {
+            return;
+        }
+
         if (currentDataBuffered < minimumBytesBuffered) {
```
Comment (zoewangg) [inline utils/src/main/java/software/amazon/awssdk/utils/async/ByteBufferStoringSubscriber.java]: Instead of enforcing maximumOutstandingDemand, can we use `byteBuffer.remaining()` as a hint  and check `outstandingDemand.get() * buffer hints + currentDataBuffered < minimumBytesBuffered`?

Because this class is used else where like https://github.com/aws/aws-sdk-java-v2/blob/master/utils/src/main/java/software/amazon/awssdk/utils/async/InputStreamSubscriber.java#L44 and it'd address the issue there as well

File: services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtRequestBodyStreamAdapter.java [hunk 3]
```diff
@@ -28,14 +28,16 @@
 @SdkInternalApi
 public final class S3CrtRequestBodyStreamAdapter implements HttpRequestBodyStream {
     private static final long MINIMUM_BYTES_BUFFERED = 1024 * 1024L;
+    // for 16 kb chunks, this limits to about 16 MB (2x the standard crt provided buffer size)
```
Comment (dagnir) [inline services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtRequestBodyStreamAdapter.java]: Where does the 16KB come from? Is it related to https://github.com/aws/aws-sdk-java-v2/pull/6542?

File: utils/src/main/java/software/amazon/awssdk/utils/async/ByteBufferStoringSubscriber.java [hunk 4]
```diff
@@ -175,12 +193,14 @@ public void onSubscribe(Subscription s) {
         storingSubscriber.onSubscribe(new DemandIgnoringSubscription(s));
         subscription = s;
         subscription.request(1);
+        outstandingDemand.incrementAndGet();
```
Comment (L-Applin) [inline utils/src/main/java/software/amazon/awssdk/utils/async/ByteBufferStoringSubscriber.java:184]: Should probably also be before the call to `request(1)`, similar to in `maybeRequestMore`

File: utils/src/main/java/software/amazon/awssdk/utils/async/ByteBufferStoringSubscriber.java (hunk 2 above)
Comment (alextwoods) [reply utils/src/main/java/software/amazon/awssdk/utils/async/ByteBufferStoringSubscriber.java]: Yeah - thats a great idea - I've updated the approach to use a sizeHint

File: services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtRequestBodyStreamAdapter.java (hunk 3 above)
Comment (alextwoods) [reply services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtRequestBodyStreamAdapter.java]: This was removed based on the sizeHint approach, but I've updated the MINIMUM_BYTES_BUFFERED to what it was prior to #3800

File: .changes/next-release/bugfix-AmazonS3-b003027.json [hunk 5]
```diff
@@ -0,0 +1,6 @@
+{
+    "type": "bugfix",
+    "category": "AWS SDK for Java v2",
+    "contributor": "",
+    "description": "Consider outstanding demand in ByteBufferStoringSubscriber before requesting more - fixes OutOfMemoryIssues in S3CrtRequestBodyStreamAdapter"
```
Comment (zoewangg) [inline .changes/next-release/bugfix-AmazonS3-b003027.json]: nit: suggesting changing `in S3CrtRequestBodyStreamAdapter` (internal API) to something like `that may occur when using AWS CRT-based S3 client to upload a large object`

**Review by zoewangg — APPROVED** [review]
