### PR TITLE
Fix paginated response iterable hasNextPage

### LINKED ISSUE #677: Dynamodb batchGetItemPaginator not working
Dynamodb batchGetItemPaginator not working. (There might be other pagination operations facing the same issue.)

## Expected Behavior
Dynamodb batchGetItemPaginator should work

## Current Behavior
It throws `DynamoDbException` when there's no next page.

```
software.amazon.awssdk.services.dynamodb.model.DynamoDbException: 1 validation error detected: Value '{}' at 'requestItems' failed to satisfy constraint: 
Member must have length greater than or equal to 1 (Service: DynamoDB, Status Code: 400, )
```
 Looking at the wirelogs, seems it tries to retrieve the next page even if there's no next page.

`batchGetItemResponse.unprocessedKeys()` is empty and is not an instance of `SdkAutoConstructMap`, so 
`BatchGetItemResponseFetcher.hasNextPage` returns true.

```java
    private class BatchGetItemResponseFetcher implements SyncPageFetcher<BatchGetItemResponse> {
        @Override
        public boolean hasNextPage(BatchGetItemResponse previousPage) {
            return previousPage.unprocessedKeys() != null
                    && !SdkAutoConstructList.class.isInstance(previousPage.unprocessedKeys())
                    && !SdkAutoConstructMap.class.isInstance(previousPage.unprocessedKeys());
        }

``` 

## Steps to Reproduce (for bugs)
```java 
        BatchGetItemIterable iterable = 
            dynamo.batchGetItemPaginator(b -> b.requestItems(attributes));
        iterable.stream().forEach(System.out::println);
```

## Your Environment

* AWS Java SDK version used: 2.0.0-preview-11
* JDK version used: 10.0.1 
* Operating System and version: Mac OS

### PR DESCRIPTION
**Pull request by zoewangg**
## Description
Fix paginated response iterable hasNextPage to check if the output token is non null or non empty if it is a collection or map type. 

`Dynamodb.batchGetItem` returns empty `unprocessedKeys` when there is no unprocessedKeys.
 
`"{"Responses":{"zoewang-TestTable":[{"attribute_foo":{"S":"test"},"hash":{"N":"0"}}]},"UnprocessedKeys":{}}"`

So unprocessedKeys is an empty map and not an instance of `SdkAutoConstructMap`. (we only create the `SdkAutoConstructMap` when it is null)

Currently, the `hasNextPage` checks if the output token is not null AND it is not instance of SdkAutoConstructMap AND not an instance of SdkAutoConstructList. So `hasNextPage` will always return true for empty list or map, which is not expected.

## Motivation and Context
Fixes #677

## Testing
`mvn clean install` local integration test.

Note: I didn't create the integration tests for the scenario where dynamodb returns us unprocessedKeys as it takes large load to trigger that scenario and the test might be flaky. I did test it for once and verified it worked.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] A short description of the change has been added to the **CHANGELOG**

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

File: core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/PaginatorUtils.java [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+
+        if (outputToken instanceof Map) {
+            return !((Map) outputToken).isEmpty();
+        }
+
+        if (outputToken instanceof Collection) {
+            return !((Collection) outputToken).isEmpty();
+        }
+
+        return true;
```
Comment (dagnir) [inline core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/PaginatorUtils.java]: nit: you can remove line 37-39 and replace this with `outputToken != null`

File: core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/PaginatorUtils.java [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+ * permissions and limitations under the License.
+ */
+
+package software.amazon.awssdk.core.internal.util;
+
+import java.util.Collection;
+import java.util.Map;
+import software.amazon.awssdk.annotations.SdkInternalApi;
+
+@SdkInternalApi
```
Comment (dagnir) [inline core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/PaginatorUtils.java]: Should this be protected? It's imported by the service modules right?

File: core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/PaginatorUtils.java (hunk 1 above)
Comment (varunnvs92) [reply core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/PaginatorUtils.java]: I like the current way instead of nested if statements. (my personal opinion)

File: core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/PaginatorUtils.java (hunk 2 above)
Comment (zoewangg) [reply core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/PaginatorUtils.java]: yup, good call. I will update it and move it outside of internal package.

File: core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/PaginatorUtils.java (hunk 1 above)
Comment (zoewangg) [reply core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/PaginatorUtils.java]: Hmm, I kind of like the current way. We can reduce 2 line of code with what you suggested.

```java
    public static <T> boolean isOutputTokenAvailable(T outputToken) {
//        if (outputToken == null) {
//            return false;
//        }

        if (outputToken instanceof Map) {
            return !((Map) outputToken).isEmpty();
        }

        if (outputToken instanceof Collection) {
            return !((Collection) outputToken).isEmpty();
        }

        return outputToken != null;
    }
```

But it seems more intuitive to me with the current way where we check null first and don't need to follow the logic all the way down if it's null.

Comment (dagnir) [reply core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/PaginatorUtils.java]: Yup, it's fine with me :)
