### PR TITLE
Fix timestamp unmarshalling off-by-one errors

### LINKED ISSUE #6064: Fast unmarshaller for JSON protocol introduces timestamp error
### Describe the bug

When unmarshalling specific timestamp values from responses which utilize a JSON-based protocol that serializes the values as UNIX_TIMESTAMP (seconds with fractional millisecond values), the value unmarshalled will sometimes be off by 1 millisecond.

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

### Expected Behavior

A response with a timestamp value of `1099510880.771` is unmarshalled as the Instant value `2004-11-03T19:41:20.771Z`

### Current Behavior

A response with a timestamp value of `1099510880.771` is unmarshalled as the Instant value `2004-11-03T19:41:20.770Z`

### Reproduction Steps

I don't have library usage reproduction steps, but the issue becomes obvious when performing the same operations as the [suspected code](https://github.com/aws/aws-sdk-java-v2/blob/f19cff67630164eaf26eabac3753f1c59471d7db/core/protocols/protocol-core/src/main/java/software/amazon/awssdk/protocols/core/NumberToInstant.java#L54):

```
Instant.ofEpochMilli((long) (value.doubleValue() * 1_000d));
```

```
$ jshell

|  Welcome to JShell -- Version 21.0.5
|  For an introduction type: /help intro

jshell> import java.time.Instant;

jshell> Instant.ofEpochMilli((long) (1099510880.771d * 1_000d));
$2 ==> 2004-11-03T19:41:20.770Z
```

This is caused by the result of `1099510880.771d * 1_000d` having IEEE 754 double precision multiplication issues:

```
jshell> 1099510880.771d * 1_000d;
$3 ==> 1.0995108807709999E12
```

### Possible Solution

Instead of simply casting the resulting double to `long`, use `Math.round(double)` to get the correctly rounded value.

I've identified two places that this incorrect logic is used:
* NumberToInstant - https://github.com/aws/aws-sdk-java-v2/blob/f19cff67630164eaf26eabac3753f1c59471d7db/core/protocols/protocol-core/src/main/java/software/amazon/awssdk/protocols/core/NumberToInstant.java#L54
* JsonUnmarshallingParser - https://github.com/aws/aws-sdk-java-v2/blob/f19cff67630164eaf26eabac3753f1c59471d7db/core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/JsonUnmarshallingParser.java#L388

### Additional Information/Context

I haven't done a deep check into how prevalent this rounding issue specifically causes off-by-one timestamps, a quick script found that dates between 2004 and 2025 **don't** appear to be impacted; however there's plenty of dates which are impacted before 2004.  

I'm working on a pull request with the possible solution above.  Feel free to contact me on slack at bnd@ if needed.

### AWS Java SDK version used

2.31.30

### JDK version used

openjdk version "21.0.5" 2024-10-15 LTS / OpenJDK Runtime Environment Corretto-21.0.5.11.1 (build 21.0.5+11-LTS) / OpenJDK 64-Bit Server VM Corretto-21.0.5.11.1 (build 21.0.5+11-LTS, mixed mode, sharing)

### Operating System and version

Mac Sequoia 15.3.2

### PR DESCRIPTION
**Pull request by sugmanue**
## Motivation and Context
Fixes #6064 

Addresses code that is impacted by double to long casts incorrectly truncating a millisecond off of fractional seconds unix timestamp values which are rounded due to IEEE 754 double precision behavior when the source value is multiplied by 1_000d.

## Modifications
Updated current truncation behavior to utilize the configured unmarshaller that uses parses the textual using a `BigDecimal` that doesn't loose any precision.

Added to that, we fixed a bug, for collections, maps and lists, to select the correct unmarshaller we need to get the type of the value instead of the type of the collection. The bug was not discovered before because to trigger it the model would need to use a non-numeric serialization for timestamps, which none of the standard JSON protocols does by default.

## Testing
Added tests for values of both non-rounded and rounded values

## Screenshots (if appropriate)
N/A

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist
- [x] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] I have added a changelog entry. Adding a new entry must be accomplished by running the `scripts/new-change` script and following the instructions. Commit the new file created by the script in `.changes/next-release` with your changes.
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

File: core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/JsonUnmarshallingParser.java [hunk 1]
```diff
@@ -159,7 +159,7 @@ private List<Object> parseList(JsonUnmarshallerContext c, SdkField<?> field, Jso
         if (isScalarType(marshallingType)) {
             MarshallingKnownType marshallingKnownType = marshallingType.getKnownType();
             while (currentToken != JsonToken.END_ARRAY) {
-                result.add(simpleValueFor(field, marshallingKnownType, c, parser, currentToken));
+                result.add(simpleValueFor(memberInfo, marshallingKnownType, c, parser, currentToken));
```
Comment (joviegas) [inline core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/JsonUnmarshallingParser.java:162]: - Can we please update the PR in modification about this change.
- Also could you please let me know the test case which covers this change for List parse and Map parse

Comment (sugmanue) [reply core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/JsonUnmarshallingParser.java:162]: 1. [List of timestamps](https://github.com/aws/aws-sdk-java-v2/blob/6747fa2abf24d9a0b686f6be3dbe2710719677eb/test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/json-core-output.json#L531)
2. [Map of timepstamps](https://github.com/aws/aws-sdk-java-v2/blob/6747fa2abf24d9a0b686f6be3dbe2710719677eb/test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/json-core-output.json#L553)

Comment (sugmanue) [reply core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/JsonUnmarshallingParser.java:162]: > Can we please update the PR in modification about this change.

Yes, I have done that as well.

Comment (joviegas) [reply core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/JsonUnmarshallingParser.java:162]: Thanks

**Review by joviegas — APPROVED** [review]
