### PR TITLE
Fix DDB Enhanced Client immutable class introspection fails for "is" prefix fields

### LINKED ISSUE #4446: TableSchema.fromImmutableClass() introspection fails when the item class has fields starting with "is"
### Describe the bug

When an immutable item class has fields that begin with "is" (e.g., "isComplete" or "isIncluded"), `TableSchema.fromImmutableClass()` throws an `ExceptionInInitializerError`. Also in stack traces this appears: `Caused by: java.lang.IllegalArgumentException: A method was found on the immutable class that does not appear to have a matching setter on the builder class. Use the @DynamoDbIgnore annotation on the method if you do not want it to be included in the TableSchema introspection`, despite no methods except getters being present in the item class, and a setter for the field actually being present for the corresponding builder class.

The `TableSchema.fromImmutableClass()` method needs to work for item class fields no matter the composition of their names. Or, the documentation needs to be updated with correct restrictions on field naming based on the behavior of [`ImmutableInstrospector`](https://github.com/aws/aws-sdk-java-v2/blob/584ccb59e770177aeaa4c3b6bda4e24015b8ece9/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/immutable/ImmutableIntrospector.java).

### Expected Behavior

TableSchema.fromImmutableClass(itemClass) should return a proper `DynamoDbTable` when called on an itemClass containing any field name, without restriction.

### Current Behavior

Errors were thrown (see description).

### Reproduction Steps

```
@DynamoDbImmutable(builder = Car.Builder.class)
public final class Car {
    private final String licensePlate;
    private final boolean isRusty;
    private final boolean isImpounded;

    private Car(final Builder b) {
        this.licensePlate = b.licensePlate;
        this.isRusty = b.isRusty;
        this.isImpounded = b.isImpounded;
    }

    public static Builder builder() {
        return new Builder();
    }

    @DynamoDbPartitionKey
    public String licensePlate() {
        return this.licensePlate;
    }

    public boolean isRusty() {
        return this.isRusty;
    }

    public boolean isImpounded() {
        return this.isImpounded;
    }

    public static final class Builder {
        private String licensePlate;
        private boolean isRusty;
        private boolean isImpounded;

        private Builder() {
        }

        public Builder licensePlate(final String licensePlate) {
            this.licensePlate = licensePlate;
            return this;
        }

        public Builder isRusty(final boolean isRusty) {
            this.isRusty = isRusty;
            return this;
        }

        public Builder isImpounded(final boolean isImpounded) {
            this.isImpounded = isImpounded;
            return this;
        }

        public Car build() {
            return new Car(this);
        }
    }
}
```

Calling `TableSchema.fromImmutableClass(Car.class)` and subsequently calling table operations on the resulting table will result in errors described above.

### Possible Solution

The behavior of the [ImmutableIntrospector](https://github.com/aws/aws-sdk-java-v2/blob/584ccb59e770177aeaa4c3b6bda4e24015b8ece9/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/immutable/ImmutableIntrospector.java) and how it parses method names is likely at large.

### Additional Information/Context

_No response_

### AWS Java SDK version used

2.20

### JDK version used

openjdk version "17.0.8" 2023-07-18 LTS OpenJDK Runtime Environment Corretto-17.0.8.7.1 (build 17.0.8+7-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.8.7.1 (build 17.0.8+7-LTS, mixed mode, sharing)

### Operating System and version

MacOS, Amazon Linux 2

### PR DESCRIPTION
**Pull request by S-Saranya1**
Fix DDB Enhanced Client immutable class introspection fails for "is" prefix fields. Fixes #4446.

## Motivation and Context
TableSchema.fromImmutableClass() fails with IllegalArgumentException when processing immutable classes that have boolean fields using "is" prefix in both getters and setters (e.g., isRusty() getter and isRusty(boolean) setter). 

Root Cause
The ImmutableIntrospector had getter, setter name normalization logic where getter normalization removes "is" prefix (isRusty() - "rusty") but setter normalization keeps "is" prefix (isRusty(boolean) - "isRusty"). This caused property matching to fail and cause this exception - `java.lang.IllegalArgumentException: A method was found on the immutable class that does not appear to have a matching setter on the builder class.`

## Modifications
Modified `normalizeSetterName()` method in `ImmutableIntrospector` to add logic for handling "is" prefix for boolean parameters with the same logic as in `normalizeGetterName()`. This ensures both getter and setter methods now normalize to the same property name, enabling proper matching during introspection.

## Testing
- Added Unit test to test this case.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] I have added a changelog entry. Adding a new entry must be accomplished by running the `scripts/new-change` script and following the instructions. Commit the new file created by the script in `.changes/next-release` with your changes.
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

File: services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/ImmutableBooleanIsPrefixTest.java [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+
+import org.junit.Test;
+import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbImmutable;
+import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
+
+/**
+ * Tests that TableSchema.fromImmutableClass() works correctly with immutable classes
+ * that have boolean fields using "is" prefix.
+ */
+public class ImmutableBooleanIsPrefixTest {
```
Comment (dagnir) [inline services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/ImmutableBooleanIsPrefixTest.java]: Can we add a test for `is` methods that are not `boolean`?

Comment (S-Saranya1) [reply services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/ImmutableBooleanIsPrefixTest.java]: Sure, added it.

**Review by dagnir — APPROVED** [review]
