### PR TITLE
Fixes for SdkAutoConstructList/Map

### LINKED ISSUE #1445: DefaultSdkAutoConstructList.equals() does not adhere to the List.equals() contract
I'm using the AWS Java SDK 2 version 2.8.3 on Windows 10 with OpenJDK 11.

The Java `java.util.List.equals()` contract requires all lists to implement `equals()` so that they compare equal to any other implementation of `List` with the same number of elements in the same order:

```java
    /**
     * Compares the specified object with this list for equality.  Returns
     * {@code true} if and only if the specified object is also a list, both
     * lists have the same size, and all corresponding pairs of elements in
     * the two lists are <i>equal</i>.  (Two elements {@code e1} and
     * {@code e2} are <i>equal</i> if {@code Objects.equals(e1, e2)}.)
     * In other words, two lists are defined to be
     * equal if they contain the same elements in the same order.  This
     * definition ensures that the equals method works properly across
     * different implementations of the {@code List} interface.
     *
     * @param o the object to be compared for equality with this list
     * @return {@code true} if the specified object is equal to this list
     */
    boolean equals(Object o);
```

Unless I'm missing it somewhere, the `software.amazon.awssdk.core.util.DefaultSdkAutoConstructList` does not implement `equals()` and therefore does not adhere to the `List.equals()` contract. The same goes for `List.hashCode()`.

### PR DESCRIPTION
**Pull request by dagnir**
## Description
Fix the implementations of equals() and hashCode() to follow the general
contract of equals and hashCode.

Also ensure that toString returns readable results.

Fixes #1445

## Motivation and Context
Bug fix.

## Testing
New unit tests.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] A short description of the change has been added to the **CHANGELOG**
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

File: core/sdk-core/src/main/java/software/amazon/awssdk/core/util/DefaultSdkAutoConstructList.java [hunk 1]
```diff
@@ -33,7 +33,7 @@
 public final class DefaultSdkAutoConstructList<T> implements SdkAutoConstructList<T> {
     private static final DefaultSdkAutoConstructList INSTANCE = new DefaultSdkAutoConstructList();
 
-    private final List impl = Collections.unmodifiableList(Collections.emptyList());
+    private final List impl = Collections.emptyList();
```
Comment (dagnir) [inline core/sdk-core/src/main/java/software/amazon/awssdk/core/util/DefaultSdkAutoConstructList.java]: Changed this because `emptyMap`/`emptyList` are already immutable so wrapping in `unmodifiable` is redundant.
