### PR TITLE
Fix HeaderUnmarshaller to compare headers ignoring cases

### LINKED ISSUE #1091: Regression: S3 User Meta Data uses case sensitive comparision
Hi,
https://github.com/aws/aws-sdk-java-v2/blob/985ec92c0dfac868b33791fe4623296c68e2feab/core/protocols/aws-xml-protocol/src/main/java/software/amazon/awssdk/protocols/xml/internal/unmarshall/HeaderUnmarshaller.java#L42

is a regression of a bug mentioned here: https://github.com/aws/aws-sdk-java/issues/704

## Your Environment

* AWS Java SDK version used: 2.4.14

### PR DESCRIPTION
**Pull request by zoewangg**
## Description
Fix xml `HeaderUnmarshaller#MAP` to compare headers ignoring cases. Checked Json HeaderUnmarshaller and it doesn't have MAP type.

## Motivation and Context
Fixes #1091 

## Testing
Added unit tests and integ tests

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [x] I have updated the Javadoc documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] A short description of the change has been added to the **CHANGELOG**
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [ ] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

File: services/s3/src/it/java/software/amazon/awssdk/services/s3/UserMetadataIntegrationTest.java [hunk 1]
```diff
@@ -83,5 +93,18 @@ public void putObject_PutsUserMetadata() throws Exception {
...
+    }
+
+    @Test
+    public void userMetadata_caseInsensitive() {
+        String caseInsensitiveMetadata = "";
+        HeadObjectResponse response =
+            s3.headObject(b -> b.bucket(BUCKET_NAME).key(KEY).overrideConfiguration(r -> r.putHeader("x-amz-metadata-test",
+                                                                                            "test")));
+
+        //assertThat(response.metadata())
```
Comment (spfink) [inline services/s3/src/it/java/software/amazon/awssdk/services/s3/UserMetadataIntegrationTest.java]: Remove?

Comment (zoewangg) [reply services/s3/src/it/java/software/amazon/awssdk/services/s3/UserMetadataIntegrationTest.java]: Yes, this test is actually unnecessary and I forgot to remove it.

**Comment by zoewangg** [comment]
Added protocol tests.
