### PR TITLE
Fix ApacheHttpClient Proxy Preemptive Auth Failure

### LINKED ISSUE #5884: ApacheHttpClient Proxy Authentication fails
### Describe the bug

Proxy Authentification fails with Status 407 when Proxy requires preemptive authentication.

My code:
```java
SdkHttpClient httpClient = ApacheHttpClient.builder()
    .proxyConfiguration(ProxyConfiguration.builder()
        .endpoint(URI.create("http://proxy.example.com"))
        .username("username")
        .password("password")
        .preemptiveBasicAuthenticationEnabled(true)
        .build())
    .build();

SnsClient snsClient = SnsClient.builder()
    .httpClient(httpClient)
    .credentialsProvider(credentials)
    .region(Region.EU_CENTRAL_1)
    .build();
``` 

A request sent by this client fails with 407 when the proxy requires preemptive authentication.
It works fine when the proxy does not.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

A request passes the proxy.

### Current Behavior

```
software.amazon.awssdk.services.sns.model.SnsException: null (Service: Sns, Status Code: 407, Request ID: null)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:38)
``` 

### Reproduction Steps

```java
SdkHttpClient httpClient = ApacheHttpClient.builder()
    .proxyConfiguration(ProxyConfiguration.builder()
        .endpoint(URI.create("http://proxy.example.com"))
        .username("username")
        .password("password")
        .preemptiveBasicAuthenticationEnabled(true)
        .build())
    .build();

SnsClient snsClient = SnsClient.builder()
    .httpClient(httpClient)
    .credentialsProvider(credentials)
    .region(Region.EU_CENTRAL_1)
    .build();

PublishRequest request = PublishRequest.builder()
    .message("Greetings")
    .topicArn("arn:aws:sns:eu-central-1:account:topic")
    .build();

PublishResponse publishResult = snsClient.publish(request);
``` 

### Possible Solution

I found a possible reason in software.amazon.awssdk.http.apache.internal.utils.ApacheUtils.

The method `addPreemptiveAuthenticationProxy` contains:
```java
BasicScheme basicAuth = new BasicScheme();
authCache.put(targetHost, basicAuth);
``` 

I added a challenge and now it works:

```java
BasicScheme basicAuth = new BasicScheme();
basicAuth.processChallenge(new BasicHeader(AUTH.PROXY_AUTH, "BASIC realm=default"));
authCache.put(targetHost, basicAuth);
``` 

### Additional Information/Context

_No response_

### AWS Java SDK version used

2.30.17

### JDK version used

openjdk version "21.0.4" 2024-07-16 LTS

### Operating System and version

Linux rodeoarch 6.12.4-arch1-1

### PR DESCRIPTION
**Pull request by S-Saranya1**
Fix ApacheHttpClient proxy authentication failure issue with preemptive authentication.

## Motivation and Context
Users configuring proxy preemptive authentication with preemptiveBasicAuthenticationEnabled set to true were experiencing 407 error which was not expected. 

Fixes #5884

## Modifications

Added synthetic challenge processing in addPreemptiveAuthenticationProxy() method to initialize BasicScheme for preemptive authentication

## Testing

Added unit test to verify preemptive authentication functionality

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] I have added a changelog entry. Adding a new entry must be accomplished by running the `scripts/new-change` script and following the instructions. Commit the new file created by the script in `.changes/next-release` with your changes.
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

File: http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/utils/ApacheUtils.java [hunk 1]
```diff
@@ -149,6 +151,11 @@ private static void addPreemptiveAuthenticationProxy(HttpClientContext clientCon
             AuthCache authCache = new BasicAuthCache();
             // Generate BASIC scheme object and add it to the local auth cache
             BasicScheme basicAuth = new BasicScheme();
+            try {
+                basicAuth.processChallenge(new BasicHeader(AUTH.PROXY_AUTH, "BASIC realm=default"));
+            } catch (Exception e) {
```
Comment (alextwoods) [inline http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/utils/ApacheUtils.java:158]: What would cause this to raise exceptions?  And if an exception is raised, should we still be putting the basicAuth into the authCache?

Comment (S-Saranya1) [reply http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/utils/ApacheUtils.java:158]: processChallenge can throw MalformedChallengeException (though extremely unlikely with our hardcoded challenge). 

> And if an exception is raised, should we still be putting the basicAuth into the authCache?

Yeah if there is exception, putting basicAuth into the authCache is not required, updated the code.

File: http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ProxyPreemptiveAuthTest.java [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+        if (httpClient != null) {
+            httpClient.close();
+        }
+        if (proxyServer != null) {
+            proxyServer.stop();
+        }
+    }
+
+    @Test
+    public void testPreemptiveAuthenticationSendsProxyAuthorizationHeader() throws Exception {
```
Comment (RanVaknin) [inline http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ProxyPreemptiveAuthTest.java]: nit: doesnt follow our test [naming conventions](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/design/NamingConventions.md)

Maybe `addPreemptiveAuthenticationProxy_whenPreemptiveAuthEnabled_shouldSendProxyAuthorizationHeader`?

File: http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ProxyPreemptiveAuthTest.java [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+        HttpExecuteRequest executeRequest = HttpExecuteRequest.builder()
+                .request(request)
+                .build();
+
+        // Execute the request - should succeed with preemptive auth header
+        HttpExecuteResponse response = httpClient.prepareRequest(executeRequest).call();
+        assertThat(response.httpResponse().statusCode()).isEqualTo(200);
+        
+        // Verify that the proxy received the request with Proxy-Authorization header
+        proxyServer.verify(WireMock.getRequestedFor(anyUrl())
```
Comment (RanVaknin) [inline http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ProxyPreemptiveAuthTest.java]: nit: can we rename proxyServer to `mockProxy` or` proxyMock`. Since this is a stubbed response it should be clear in the name.

File: http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ProxyPreemptiveAuthTest.java [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+import software.amazon.awssdk.http.SdkHttpMethod;
+import software.amazon.awssdk.http.SdkHttpRequest;
+
+/**
+ * Tests proxy preemptive authentication functionality.
+ * 
+ * Verifies that when preemptiveBasicAuthenticationEnabled(true) is configured,
+ * the Proxy-Authorization header is sent with the first request to the proxy.
+ */
+public class ProxyPreemptiveAuthTest {
```
Comment (RanVaknin) [inline http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ProxyPreemptiveAuthTest.java]: I know the original issue does not ask for it, but since we are testing the not-preemptive auth codepath, if possible, can we also add a test case for the regular auth codepath? I don't see that we have coverage for this. 

something like:

```java
proxyServer.stubFor(...407...)
proxyServer.stubFor(...200...)

httpClient.prepareRequest(executeRequest).call();

proxyServer.verify(2, anyRequestedFor(anyUrl())); // verify that there are 2 requests being sent
proxyServer.verify(1, anyRequestedFor(anyUrl()).withoutHeader("Proxy-Authorization"));
proxyServer.verify(1, anyRequestedFor(anyUrl()).withHeader("Proxy-Authorization", matching("Basic .+")));
```

File: http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ProxyPreemptiveAuthTest.java (hunk 2 above)
Comment (S-Saranya1) [reply http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ProxyPreemptiveAuthTest.java]: Yes, Updated it.

File: http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ProxyPreemptiveAuthTest.java (hunk 3 above)
Comment (S-Saranya1) [reply http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ProxyPreemptiveAuthTest.java]: Sure, renamed it to mockProxy.

File: http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ProxyPreemptiveAuthTest.java (hunk 4 above)
Comment (S-Saranya1) [reply http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ProxyPreemptiveAuthTest.java]: Yeah, added the test case for not-preemptive auth codepath as well.

File: http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ProxyPreemptiveAuthTest.java [hunk 5]
```diff
@@ -0,0 +1,148 @@
...
+        HttpExecuteResponse response = httpClient.prepareRequest(executeRequest).call();
+        assertThat(response.httpResponse().statusCode()).isEqualTo(200);
+
+        mockProxy.verify(1, anyRequestedFor(anyUrl()));
+        mockProxy.verify(WireMock.getRequestedFor(anyUrl())
+                .withHeader("Proxy-Authorization", matching("Basic .+")));
+    }
+
+    @Test
+    public void addPreemptiveAuthenticationProxy_whenPreemptiveAuthDisabled_shouldUseChallengeResponseAuth() throws Exception {
```
Comment (RanVaknin) [inline http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ProxyPreemptiveAuthTest.java]: this should be a separate test file / or even directory since it's not testing the preemptive auth codepath.
Also the name of the test should be different for the same reason

Comment (S-Saranya1) [reply http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ProxyPreemptiveAuthTest.java]: Updated the test file name to `ApacheHttpClientProxyAuthTest` and kept both tests in the same file.

**Review by RanVaknin — APPROVED** [review]

**Review by alextwoods — APPROVED** [review]
