### PR TITLE
Fix #585 RetryOnExceptions should consider subclasses of exceptions.

### LINKED ISSUE #585: Retry on IOException not working as expected
## Expected Behavior
By default, the SDK should retry on any kind of `IOException` as specified by `SdkDefaultRetrySettings` ( https://github.com/aws/aws-sdk-java-v2/blob/5872b1536ed4434c3297c261b546e482060e61be/core/src/main/java/software/amazon/awssdk/core/internal/retry/SdkDefaultRetrySetting.java#L64 )

## Current Behavior
The SDK only retry if the exception was exactly an `IOException` and ignores all subclasses. As a result exceptions like `ClosedChannelException` or `SSLException` don't trigger a retry.

## Possible Solution
2 fixes are possible:

- Explicitly defines specific `IOException` we want to handle by default
- Modify `RetryOnExceptionsCondition` to check if the thrown exception is a subclass of one of the `exceptionsToRetryOn` using `isAssignableFrom()`

## Context
Call to dynamodb sometime fails because with `ClosedChannelException` or `SSLException` and are not retried.

## Your Environment
* AWS Java SDK version used: 2.0.0-preview-10

### PR DESCRIPTION
**Pull request by madgnome**
## Description
Modify `RetryOnExceptionsCondition` to consider subclasses of exception defined in `exceptionsToRetryOn`, e.g. `SSLException` will be retried because it's a subclass of `IOException` if `IOException` is in `exceptionsToRetryOn`

## Motivation and Context
#585 

## Testing
Added unit test for this behaviour.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [ ] A short description of the change has been added to the **CHANGELOG**

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Comment by madgnome** [comment]
The test `ResponseTransformerTest.downloadToOutputStreamDoesNotRetry` is now failing making me wonder if this fix is the right solution.

**Comment by millems** [comment]
I think `ResponseTransformerTest.downloadToOutputStreamDoesNotRetry` was passing before, because it was relying on this issue. I think it's a bug that we're currently retrying on anything other than RetryableException thrown from ResponseTransformer.

@zoewangg @shorea Can you confirm?

**Comment by shorea** [comment]
Yes that's an existing bug. I think at one point we were wrapping the response handler and letting retryable exceptions go through as is and wrapping everything else in NonRetryableException.

**Comment by zoewangg** [comment]
Yes, one way to fix it is to make changes in`ResponseTransformer` to catch those non-retryable IOException, such as the ones thrown from `toOutputStream` and wrap it with a non-retrable SdkException.

**Comment by millems** [comment]
I'd say everything thrown from a ResponseTransformer that isn't RetryableException shouldn't be retried.

File: core/src/main/java/software/amazon/awssdk/core/sync/ResponseTransformer.java [hunk 1]
```diff
@@ -157,7 +158,11 @@ default boolean needsConnectionLeftOpen() {
      */
     static <ResponseT> ResponseTransformer<ResponseT, ResponseT> toOutputStream(OutputStream outputStream) {
         return (resp, in) -> {
-            IoUtils.copy(in, outputStream);
+            try {
+                IoUtils.copy(in, outputStream);
```
Comment (shorea) [inline core/src/main/java/software/amazon/awssdk/core/sync/ResponseTransformer.java]: Ideally we'd do this at a higher layer so that any response transformer implementation that is passed in gets it's exceptions converted to non-retryable exceptions unless they explicitly throw a retryable exception.

Comment (madgnome) [reply core/src/main/java/software/amazon/awssdk/core/sync/ResponseTransformer.java]: Yeah that would be nice indeed. 
Unfortunately `ResponseTransformer` is used all over the place so there isn't a higher layer to put the logic currently. 

I guess we could introduce one within this class, something like:

```java
@FunctionalInterface
@SdkPublicApi
public interface ResponseTransformer<ResponseT, ReturnT> {
    /**
     * Process the response contents.
     *
     * @param response    Unmarshalled POJO response
     * @param inputStream Input stream of streamed data.
     * @return Transformed type.
     * @throws Exception if any error occurs during processing of the response. This will be re-thrown by the SDK, possibly
     *                   wrapped in an {@link SdkClientException}.
     */
    default ReturnT transform(ResponseT response, AbortableInputStream inputStream) throws Exception {
        try {
            return apply(response, inputStream);
        } catch (RetryableException e) {
            throw e;
        } catch (Exception e) {
            throw new NonRetryableException(e);
        }
    }

    ReturnT apply(ResponseT response, AbortableInputStream inputStream) throws Exception;
}
```

I'm not familiar with this codebase so I may be completely off track 🤷‍♂️

File: core/sdk-core/src/main/java/software/amazon/awssdk/core/sync/ResponseTransformer.java [hunk 2]
```diff
@@ -78,7 +79,17 @@
...
+        try {
+            return apply(response, inputStream);
+        } catch (RetryableException e) {
+            throw e;
+        } catch (Exception e) {
+            throw new NonRetryableException(e);
+        }
+    }
+
+    ReturnT apply(ResponseT response, AbortableInputStream inputStream) throws Exception;
```
Comment (zoewangg) [inline core/sdk-core/src/main/java/software/amazon/awssdk/core/sync/ResponseTransformer.java]: hmm, not sure why checkstyle doesn't fail on this, but `apply` is conflicting with kotlin function name. Can we make `apply` default method and `transform` abstract method?

https://github.com/aws/aws-sdk-java-v2/blob/0e14d03bfab5440ef0380bf637fed9304e66e2c2/build-tools/src/main/resources/software/amazon/awssdk/checkstyle.xml#L255-L260

File: core/sdk-core/src/main/java/software/amazon/awssdk/core/sync/ResponseTransformer.java [hunk 3]
```diff
@@ -108,7 +119,7 @@ default boolean needsConnectionLeftOpen() {
 
                 // If the write failed because of the state of the file, don't retry the request.
                 if (copyException instanceof FileAlreadyExistsException || copyException instanceof DirectoryNotEmptyException) {
-                    throw new IOException(copyError, copyException);
+                    throw (new IOException(copyError, copyException));
```
Comment (zoewangg) [inline core/sdk-core/src/main/java/software/amazon/awssdk/core/sync/ResponseTransformer.java]: redundant parentheses here.

**Comment by madgnome** [comment]
Actioned code review remarks, rebased and squashed.
