### PR TITLE
Fix S3 exception unmarshalling #297

### LINKED ISSUE #297: HeadObjectRequest exception
**Expected Behavior**

A S3 HeadObjectRequest for a missing object throws NoSuchKeyException

**Current Behavior**

A S3 HeadObjectRequest for a missing object throws NPE

**Possible Solution**

Make behavior match v1.

**Context**

Using a HeadObjectRequest to check if the same object already exists before doing a put as to prevent an overwrite.

**Your Environment**

AWS Java SDK version used: https://mvnrepository.com/artifact/software.amazon.awssdk/bom/2.0.0-preview-5
JDK version used: Oracle JDK 1.8.0_u151
Operating System and version: Win 10 in Wildfly 11.0.0.Final Application Server

```
2017-11-18 19:24:47,259 INFO  [software.amazon.awssdk.core.http.DefaultErrorResponseHandler] (EJB default - 1) Unable to read input stream to string (Invocation Id:016f1163-c297-ab01-0f2a-1ddf21c4694b): java.lang.NullPointerException
        at software.amazon.awssdk.utils.IoUtils.toByteArray(IoUtils.java:46)
        at software.amazon.awssdk.utils.IoUtils.toString(IoUtils.java:60)
        at software.amazon.awssdk.core.http.DefaultErrorResponseHandler.contentToString(DefaultErrorResponseHandler.java:115)
        at software.amazon.awssdk.core.http.DefaultErrorResponseHandler.documentFromContent(DefaultErrorResponseHandler.java:105)
        at software.amazon.awssdk.core.http.DefaultErrorResponseHandler.createAse(DefaultErrorResponseHandler.java:83)
        at software.amazon.awssdk.core.http.DefaultErrorResponseHandler.handle(DefaultErrorResponseHandler.java:70)
        at software.amazon.awssdk.core.http.DefaultErrorResponseHandler.handle(DefaultErrorResponseHandler.java:45)
        at software.amazon.awssdk.core.internal.http.response.AwsErrorResponseHandler.handleAse(AwsErrorResponseHandler.java:52)
        at software.amazon.awssdk.core.internal.http.response.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:43)
        at software.amazon.awssdk.core.internal.http.response.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:31)
        at software.amazon.awssdk.core.http.pipeline.stages.HandleResponseStage.handleErrorResponse(HandleResponseStage.java:119)
        at software.amazon.awssdk.core.http.pipeline.stages.HandleResponseStage.handleResponse(HandleResponseStage.java:76)
        at software.amazon.awssdk.core.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:61)
        at software.amazon.awssdk.core.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:44)
        at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
        at software.amazon.awssdk.core.http.pipeline.stages.TimerExceptionHandlingStage.execute(TimerExceptionHandlingStage.java:40)
        at software.amazon.awssdk.core.http.pipeline.stages.TimerExceptionHandlingStage.execute(TimerExceptionHandlingStage.java:30)
        at software.amazon.awssdk.core.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:141)
        at software.amazon.awssdk.core.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:107)
        at software.amazon.awssdk.core.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:66)
        at software.amazon.awssdk.core.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:47)
        at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
        at software.amazon.awssdk.core.http.StreamManagingStage.execute(StreamManagingStage.java:62)
        at software.amazon.awssdk.core.http.StreamManagingStage.execute(StreamManagingStage.java:46)
        at software.amazon.awssdk.core.http.pipeline.stages.FailureProgressPublishingStage.execute(FailureProgressPublishingStage.java:41)
        at software.amazon.awssdk.core.http.pipeline.stages.FailureProgressPublishingStage.execute(FailureProgressPublishingStage.java:30)
        at software.amazon.awssdk.core.http.pipeline.stages.ClientExecutionTimedStage.executeWithTimer(ClientExecutionTimedStage.java:69)
        at software.amazon.awssdk.core.http.pipeline.stages.ClientExecutionTimedStage.execute(ClientExecutionTimedStage.java:53)
        at software.amazon.awssdk.core.http.pipeline.stages.ClientExecutionTimedStage.execute(ClientExecutionTimedStage.java:37)
        at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
        at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
        at software.amazon.awssdk.core.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:35)
        at software.amazon.awssdk.core.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:24)
        at software.amazon.awssdk.core.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:325)
        at software.amazon.awssdk.core.client.SyncClientHandlerImpl.doInvoke(SyncClientHandlerImpl.java:142)
        at software.amazon.awssdk.core.client.SyncClientHandlerImpl.invoke(SyncClientHandlerImpl.java:124)
        at software.amazon.awssdk.core.client.SyncClientHandlerImpl.execute(SyncClientHandlerImpl.java:99)
        at software.amazon.awssdk.core.client.SyncClientHandlerImpl.execute(SyncClientHandlerImpl.java:75)
        at software.amazon.awssdk.core.client.SdkClientHandler.execute(SdkClientHandler.java:47)
        at software.amazon.awssdk.services.s3.DefaultS3Client.headObject(DefaultS3Client.java:1620)
```

### PR DESCRIPTION
**Pull request by zoewangg**
## Description
S3 exception unmarshalling. 
Fixes #297 #123 #147
**Note**: 
this will only fix exception unmarshalling for s3 error responses that are actually containing the error details such as `getObject`, `getObjectAcl`,
for operations such as `headObject`, `headBucket`, since s3 is not returning us any error details, we can't marshal it to the correct exceptions. we need to find a way to remove the exception from the javadoc.

## Testing
Added integration tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [x] I have updated the Javadoc documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] A short description of the change has been added to the **CHANGELOG**

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Comment by shorea** [comment]
Why can't we solve this at generation time? Otherwise we have to hand write every exception unmarshaller going forward.

**Comment by zoewangg** [comment]
Updated to use template to generate exception unmarshaller

File: services/s3/src/main/java/software/amazon/awssdk/services/s3/transform/S3ExceptionUnmarshaller.java [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+import javax.xml.xpath.XPath;
+import org.w3c.dom.Node;
+import software.amazon.awssdk.core.AmazonServiceException;
+import software.amazon.awssdk.core.runtime.transform.StandardErrorUnmarshaller;
+import software.amazon.awssdk.utils.StringUtils;
+
+/**
+ * Base exception unmarshaller for S3.
+ */
+public abstract class S3ExceptionUnmarshaller extends StandardErrorUnmarshaller {
```
Comment (shorea) [inline services/s3/src/main/java/software/amazon/awssdk/services/s3/transform/S3ExceptionUnmarshaller.java]: Minor but does it get any behavior from StandardErrorUnmarshaller or can it extend AbstractErrorUnmarshaller instead?

File: codegen/src/main/resources/templates/rest-xml/s3/ExceptionUnmarshaller.ftl [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+import org.w3c.dom.Node;
+import javax.annotation.Generated;
+
+import software.amazon.awssdk.core.AmazonServiceException;
+import software.amazon.awssdk.core.util.XpathUtils;
+
+import ${metadata.fullModelPackageName}.${shape.shapeName};
+
+@Generated("software.amazon.awssdk:aws-java-sdk-code-generator")
+public class ${shape.shapeName}Unmarshaller extends software.amazon.awssdk.services.s3.transform.S3ExceptionUnmarshaller {
```
Comment (spfink) [inline codegen/src/main/resources/templates/rest-xml/s3/ExceptionUnmarshaller.ftl]: Import this?

File: services/s3/src/main/java/software/amazon/awssdk/services/s3/transform/S3ExceptionUnmarshaller.java [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+        }
+
+        AmazonServiceException ase = newException(message);
+        ase.setErrorCode(errorCode);
+        ase.setRequestId(requestId);
+
+        return ase;
+    }
+
+    public abstract String getErrorCode();
```
Comment (shorea) [inline services/s3/src/main/java/software/amazon/awssdk/services/s3/transform/S3ExceptionUnmarshaller.java]: Minor but you can just pass this in the constructor.

File: services/s3/src/main/java/software/amazon/awssdk/services/s3/transform/S3ExceptionUnmarshaller.java (hunk 1 above)
Comment (zoewangg) [reply services/s3/src/main/java/software/amazon/awssdk/services/s3/transform/S3ExceptionUnmarshaller.java]: good catch!

File: services/s3/src/main/java/software/amazon/awssdk/services/s3/transform/S3ExceptionUnmarshaller.java (hunk 3 above)
Comment (zoewangg) [reply services/s3/src/main/java/software/amazon/awssdk/services/s3/transform/S3ExceptionUnmarshaller.java]: good catch!!

File: codegen/src/main/resources/templates/rest-xml/s3/ExceptionUnmarshaller.ftl (hunk 2 above)
Comment (zoewangg) [reply codegen/src/main/resources/templates/rest-xml/s3/ExceptionUnmarshaller.ftl]: yeah, fixed!
> We'll need to refactor this when we refactor (un)marshallers but works for now.

yes, didn't know that. missed #30 :(
