### PR TITLE
DynamoDB Enhanced: Bugfix for handling '+' character in attribute names

### LINKED ISSUE #3058: DynamoDbEnhanced queries fail on attributes that contain `+` sign.
### Describe the bug

Queries on attribute names that contain `+` sign (for example `FirstName+LastName`) fail when using the DynamoDbEnhanced client.

### Expected behavior

Querying on attribute names that contain `+` sign should be possible.

### Current behavior

Users get the following exception
```
software.amazon.awssdk.services.dynamodb.model.DynamoDbException: ExpressionAttributeNames contains invalid key: Syntax error; key: "#AMZN_MAPPED_FirstName+LastName" 
```

### Steps to Reproduce

Create a table

Run a query with a key that includes + sign. Example
```
aws dynamodb query \
    --table-name MyTable \
    --key-condition-expression "#AMZN_MAPPED_FirstName+LastName = :AMZN_MAPPED_FirstName+LastName" \
    --expression-attribute-names '{"#AMZN_MAPPED_FirstName+LastName": "Table's PK"}'
    --expression-attribute-values  '{":AMZN_MAPPED_FirstName+LastName":{"S":"AnyValue"}}' 
```

The outcome will be 
```
software.amazon.awssdk.services.dynamodb.model.DynamoDbException: ExpressionAttributeNames contains invalid key: Syntax error; key: "#AMZN_MAPPED_Node+Operation" 
```

The same applies for the attribute values key. In that case the exception will be
```
software.amazon.awssdk.services.dynamodb.model.DynamoDbException: ExpressionAttributeValues contains invalid key: Syntax error; key: ":AMZN_MAPPED_Node+Operation" 
```

Note, the example I was running was on a GSI but I think the same would apply on any query.

### Possible Solution

The EnhancedDynamoDbClient uses  `"#AMZN_MAPPED_" + cleanAttributeName(<attributeName>)" ` and `":#AMZN_MAPPED_" + cleanAttributeName(<attributeName>)"` as placeholders in query expressions. 
https://github.com/aws/aws-sdk-java-v2/blob/584ccb59e770177aeaa4c3b6bda4e24015b8ece9/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/conditional/EqualToConditional.java

`+` does not seem to be allowed in those keys.

The `cleanAttributeName` method should also escape `+` signs.
https://github.com/aws/aws-sdk-java-v2/blob/584ccb59e770177aeaa4c3b6bda4e24015b8ece9/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/EnhancedClientUtils.java

Note: The same method is also used for projection expressions. My guess is that also does not allow `+` signs but I have not tested.
https://github.com/aws/aws-sdk-java-v2/blob/6eb75be0be780319e491e2f37a61c83d33a58885/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/ProjectionExpression.java

### Context

We had to recreate our table and GSIs as to not use + in the attribute names. We replaced them with #.

### AWS Java SDK version used

2.0

### JDK version used

JDK 11

### Operating System and version

Any

### PR DESCRIPTION
**Pull request by debora-ito**
DynamoDB expression attribute names should have only alphanumeric characters. The Enhanced Client manually replaces special characters with placeholders by calling `cleanAttributeName(String key)` but it was not replacing the `+` character.

## Motivation and Context

Fixes #3058.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [x] Local run of `mvn install` succeeds
- [ ] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] I have added a changelog entry. Adding a new entry must be accomplished by running the `scripts/new-change` script and following the instructions. Commit the new file created by the script in `.changes/next-release` with your changes.
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

File: services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/EnhancedClientUtils.java [hunk 1]
```diff
@@ -54,6 +54,7 @@ public static String cleanAttributeName(String key) {
                 || chars[i] == '.'
                 || chars[i] == '-'
                 || chars[i] == '#'
+                || chars[i] == '+'
```
Comment (Bennett-Lynch) [inline services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/EnhancedClientUtils.java:57]: Nit: Can also consider a `Set<Character>`.

**Review by Bennett-Lynch — APPROVED** [review]

File: services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/EnhancedClientUtils.java (hunk 1 above)
Comment (debora-ito) [reply services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/EnhancedClientUtils.java:57]: For storing the special characters, you mean?
I'll change the next time a special character needs to be added :)
