### PR TITLE
Fix #1268

### LINKED ISSUE #1268: NPE in ByteArrayAsyncResponseTransformer
When exception below happened:
`software.amazon.awssdk.core.exception.SdkClientException: Unable to load credentials`
It will trigger NPE below:

 ```
java.lang.NullPointerException

        at software.amazon.awssdk.core.internal.async.ByteArrayAsyncResponseTransformer.exceptionOccurred(ByteArrayAsyncResponseTransformer.java:66)

        at software.amazon.awssdk.services.s3.DefaultS3AsyncClient.lambda$getObject$0(DefaultS3AsyncClient.java:1889)

        at software.amazon.awssdk.utils.FunctionalUtils.runAndLogError(FunctionalUtils.java:40)

        at software.amazon.awssdk.services.s3.DefaultS3AsyncClient.getObject(DefaultS3AsyncClient.java:1888)

        at com.amazon.magnolio.s3.MagnolioS3ClientV2.asyncReadRange(MagnolioS3ClientV2.java:216)
```

It seems the private volatile CompletableFuture<byte[]> cf;  is not initialized before the exceptionOccurred is triggered.
 

* AWS Java SDK version used: 
* JDK version used: 1.8
* Operating System and version: Linux

### PR DESCRIPTION
**Pull request by varunnvs92**
* Fix for #1268
* Add an execution attribute to store the `CompletableFuture` of initial request attempt (for async streaming APIs)
* AsyncRetryableStage clear the execution attribute for retries if present so that `prepare()` method is called

**Edit:**
**Issue:**
SDK threw a ClientException as credentials cannot be resolved. In the catch block, SDK calls `asyncResponseTransformer.exceptionOccurred()` which will throw NPE as `prepare()` method is not called first which is the point the initialization. The fix moves the `prepare` call earlier into the call stack.

```
        } catch (Throwable t) {
            runAndLogError(log, "Exception thrown in exceptionOccurred callback, ignoring",
                    () -> asyncResponseTransformer.exceptionOccurred(t));
            return CompletableFutureUtils.failedFuture(t);
        }
```

### CODE REVIEW

File: core/sdk-core/src/main/java/software/amazon/awssdk/core/client/handler/BaseAsyncClientHandler.java [hunk 1]
```diff
@@ -73,7 +75,12 @@ protected BaseAsyncClientHandler(SdkClientConfiguration clientConfiguration,
         ClientExecutionParams<InputT, OutputT> executionParams,
         AsyncResponseTransformer<OutputT, ReturnT> asyncResponseTransformer) {
 
+        // For streaming requests, prepare() should be called as early as possible to avoid NPE in client
+        // See https://github.com/aws/aws-sdk-java-v2/issues/1268
+        CompletableFuture<ReturnT> asyncTransformerFuture = asyncResponseTransformer.prepare();
```
Comment (zoewangg) [inline core/sdk-core/src/main/java/software/amazon/awssdk/core/client/handler/BaseAsyncClientHandler.java]: can we write a unit test for it to verify it's being called so that we know if it accidentally gets removed in the future?

File: core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/SdkInternalExecutionAttribute.java [hunk 2]
```diff
@@ -30,6 +32,13 @@
      */
     public static final ExecutionAttribute<Boolean> IS_FULL_DUPLEX = new ExecutionAttribute<>("IsFullDuplex");
 
+    /**
+     * The key to store the {@link CompletableFuture} returned by {@link AsyncResponseTransformer#prepare()} method
+     * in the first attempt of a request. This is used only for async streaming requests
+     */
+    public static final ExecutionAttribute<CompletableFuture<?>> STREAMING_ASYNC_RESPONSE_TRANSFORMER_FUTURE =
```
Comment (zoewangg) [inline core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/SdkInternalExecutionAttribute.java]: `AsyncResponseTransformer` is only used for streaming operations, should we drop the prefix `STREAMING_`?

File: core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/RequestExecutionContext.java [hunk 3]
```diff
@@ -124,6 +127,10 @@ public void requestProvider(AsyncRequestBody publisher) {
         requestProvider = publisher;
     }
 
+    public CompletableFuture streamingAsyncResponseTransformerFuture() {
```
Comment (zoewangg) [inline core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/RequestExecutionContext.java]: Let's use wild card `CompletableFuture<?>` instead of raw type.
`asyncResponseTransformerFuture()` if we decide to drop the prefix

File: core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncRetryableStage.java [hunk 4]
```diff
@@ -200,6 +202,14 @@ private void beforeExecute() {
 
             // Before each attempt, Modify the context to use original request body provider
             context.requestProvider(originalRequestBody);
+
+            // For streaming requests, future from the execution attributes (set in BaseAsyncClientHandler#execute method)
+            // should be used on first attempt. For all retry attempts, clear the value so that prepare() method is
+            // called (in MakeAsyncHttpRequestStage) to get a new future
+            if (requestCount > 1 && context.streamingAsyncResponseTransformerFuture() != null) {
+                context.executionAttributes().putAttribute(STREAMING_ASYNC_RESPONSE_TRANSFORMER_FUTURE, null);
```
Comment (zoewangg) [inline core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncRetryableStage.java]: Is there any reason we are not adding `asyncResponseTransformerFuture(CompletableFuture<?> completableFuture)` in `RequestExecutionContext`?

File: services/s3/src/test/java/Testing.java [hunk 5]
```diff
@@ -0,0 +1,25 @@
+import java.net.URI;
+import java.nio.file.Paths;
+import org.junit.Test;
+import software.amazon.awssdk.auth.credentials.AwsCredentialsProviderChain;
+import software.amazon.awssdk.auth.credentials.EnvironmentVariableCredentialsProvider;
+import software.amazon.awssdk.auth.credentials.SystemPropertyCredentialsProvider;
+import software.amazon.awssdk.services.s3.S3AsyncClient;
+
+public class Testing {
```
[the remark this answers is not in the document]
Comment (varunnvs92) [reply services/s3/src/test/java/Testing.java]: This was mistakenly included in the PR. Removed

File: core/sdk-core/src/main/java/software/amazon/awssdk/core/client/handler/BaseAsyncClientHandler.java (hunk 1 above)
Comment (varunnvs92) [reply core/sdk-core/src/main/java/software/amazon/awssdk/core/client/handler/BaseAsyncClientHandler.java]: Added

File: core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/SdkInternalExecutionAttribute.java (hunk 2 above)
Comment (varunnvs92) [reply core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/SdkInternalExecutionAttribute.java]: Sure, will remove

File: core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/RequestExecutionContext.java (hunk 3 above)
Comment (varunnvs92) [reply core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/RequestExecutionContext.java]: Done

File: core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncRetryableStage.java (hunk 4 above)
Comment (varunnvs92) [reply core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncRetryableStage.java]: No particular reason. There were not lot of methods in the class that are modifying the state, so didn't add new method for this.

File: services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/handlers/AsyncResponseTransformerTest.java [hunk 6]
```diff
@@ -0,0 +1,55 @@
...
+import software.amazon.awssdk.services.s3.S3AsyncClient;
+
+@RunWith(MockitoJUnitRunner.class)
+public class AsyncResponseTransformerTest {
+
+    @Mock
+    private AsyncResponseTransformer asyncResponseTransformer;
+
+    @Test
+    public void AsyncResponseTransformerPrepareCalled_BeforeCredentailsResolution() {
```
Comment (varunnvs92) [inline services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/handlers/AsyncResponseTransformerTest.java]: Verified test fails before this change

Comment (zoewangg) [reply services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/handlers/AsyncResponseTransformerTest.java]: nice

File: core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/RequestExecutionContext.java (hunk 3 above)
Comment (varunnvs92) [reply core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/RequestExecutionContext.java]: Compiler is not happy with wild card when assigning it to generic field. Reverted back to raw type

**Comment by varunnvs92** [comment]
Added changelog. Started integ tests to make sure no regression is introduced. Will merge after integ tests pass

File: core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/RequestExecutionContext.java (hunk 3 above)
Comment (zoewangg) [reply core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/RequestExecutionContext.java]: Hmm, are we using raw type CompletableFuture any where else?

Comment (varunnvs92) [reply core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/RequestExecutionContext.java]: No, this is the only place afaik. Compiler error [here](https://github.com/aws/aws-sdk-java-v2/blob/565175424144cf063bcd61df484a55125ccb5fca/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MakeAsyncHttpRequestStage.java#L95) if wild card is used.

**Comment by zoewangg** [comment]
Stability tests are almost ready to be merged #1284 if you want to test it out :)
