### PR TITLE
IntelliJ inspections

### LINKED ISSUE #1541: Use Java 8 language features
## Expected Behavior
Since the SDK has a minimum Java 8 requirement, it should be using Java 8 language features.

## Current Behavior
The SDK code has [redundant type parameters](https://github.com/aws/aws-sdk-java-v2/blob/master/codegen/src/main/java/software/amazon/awssdk/codegen/customization/processors/ShapeModifiersProcessor.java#L202), [comparisons replaceable with Objects.equals](https://github.com/aws/aws-sdk-java-v2/blob/master/services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/ConfiguredS3SdkHttpRequest.java#L66), and others that are indicative of older Java language levels. 

## Possible Solution
I suggest using IntelliJ's tools to update the code style to leverage Java 8.

## Steps to Reproduce (for bugs)
n/a

## Context
If the code is going to build for a minimum of Java 8, then those available language features should be used throughout the code.
IntelliJ provides pretty good inspection tools. The results still need to be reviewed, but it's pretty easy to go through and fix a bunch of these.

## Your Environment
* JDK version used: 1.8

### PR DESCRIPTION
**Pull request by jeffalder**
## Description
Runs IntelliJ's automatic inspections and fixes a number of issues.

## Motivation and Context
Many places are still using old Java syntax and style. This PR includes several fixes including lambda improvements, redundancy removal, and minor performance changes.

Fixes #1541 

The biggest offender vis-a-vis inspections is Javadoc issues; since this project does indeed use Javadoc I'd fix that separately.

Let me know if this PR is too big; I separated the commits to make it easier to see what's going on.

## Testing
mvn install
visual inspection of all changes for potential side-effects. I opted not to apply some.

## Screenshots (if appropriate)
n/a

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [x] My change requires a change to the Javadoc documentation
- [x] I have updated the Javadoc documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] A short description of the change has been added to the **CHANGELOG**
- [x] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Comment by millems** [comment]
I'll review and let you know! Thanks again.

File: core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonMarshaller.java [hunk 1]
```diff
@@ -27,11 +27,7 @@
 @SdkInternalApi
 public interface JsonMarshaller<T> extends Marshaller<T> {
```
Comment (millems) [inline core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonMarshaller.java]: Nit: Can we make this a `@FunctionalInterface`?

File: http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/conn/SdkTlsSocketFactory.java [hunk 2]
```diff
@@ -82,7 +82,7 @@ protected final void prepareSocket(final SSLSocket socket) {
             }
         }
         if (target.size() > 0) {
-            String[] enabling = target.toArray(new String[target.size()]);
+            String[] enabling = target.toArray(new String[0]);
```
Comment (millems) [inline http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/conn/SdkTlsSocketFactory.java]: Isn't target.size() a tiny bit more efficient?

Comment (jeffalder) [reply http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/conn/SdkTlsSocketFactory.java]: One would think! I was very suspicious of this recommendation by IntelliJ. However, this [extremely well-written, detailed, and thorough article](https://shipilev.net/blog/2016/arrays-wisdom-ancients/#_conclusion) explains why that is not the case, and hasn't been since mid-Java 6.

From the conclusion: `target.size()` cannot be predictively optimized the way the constant `0` can. And existing arrays need to be explicitly zeroed, but newly-allocated arrays can bypass the zeroing if the JVM knows it's going to be fully initialized.

Admittedly, this is a HotSpot-specific optimization, but I would hazard a guess that 75%+ of the SDK users are on HotSpot or a derivative (that includes Corretto, no?). This is also a very micro-optimization for this use case; I can't imagine there are a lot of enabled TLS protocols, or that the array is frequently copied.

File: core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonMarshaller.java (hunk 1 above)
Comment (jeffalder) [reply core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonMarshaller.java]: Done in 126fb115ec05f4648e133201d9132be970a2bd66. I also did the Query and Xml marshallers in 130d1c88f63d20779bcca1b9df25b7cf4a6382d2 because I like consistency.

**Comment by jeffalder** [comment]
I'm leaving this open to ensure I get a clean PR build. You can squash-merge if you approve or I can squash Wednesday night.

File: core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonMarshaller.java (hunk 1 above)
Comment (millems) [reply core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonMarshaller.java]: Nice!

File: http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/conn/SdkTlsSocketFactory.java (hunk 2 above)
Comment (millems) [reply http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/conn/SdkTlsSocketFactory.java]: TIL. I didn't know it could avoid zeroing the array. Cool!

**Comment by jeffalder** [comment]
@millems squashed and rebased!

**Comment by millems** [comment]
@jeffalder As usual, thanks for the awesome work!
