### PR TITLE
DynamoDBEnhanced - Fix for handling special characters in Query

### LINKED ISSUE #3139: DynamoDbEnhanced queries fail on attributes that contain `/` sign
### Describe the bug

Similar bug reported before https://github.com/aws/aws-sdk-java-v2/issues/3058 for `+`. sign, I have attribute name contains `/` which works fine with V1 SDK [DynamoDBMapper](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.html) but now with enhanced client it throws
```ExpressionAttributeNames contains invalid key: Syntax error; key: "#AMZN_MAPPED_RecFlowPriority/TimeScheduledForReconciliation"```

### Expected behavior

Querying on attribute names that contain `/` sign should be possible.

### Current behavior

ExpressionAttributeNames contains invalid key: Syntax error; key: "#AMZN_MAPPED_RecFlowPriority/TimeScheduledForReconciliation"

### Steps to Reproduce

Run a query with 
Construct a table with a partition key and sort key, make the sort key attribute name contains `/`

do a query with 
dynamoDBTable.query(r -> r.queryConditional(sortBeginsWith(s -> s.partitionValue("some key").sortValue("some value"))));

### Possible Solution

similar to whats patched in https://github.com/aws/aws-sdk-java-v2/issues/3058

### Context

_No response_

### AWS Java SDK version used

2.0

### JDK version used

openjdk version "1.8.0_322"

### Operating System and version

Mac OS 10.15.7

### PR DESCRIPTION
**Pull request by debora-ito**
The DynamoDB Enhanced Client replaces special characters with placeholders by calling cleanAttributeName(String key) but it was not replacing the / character. 

I also included several other special characters that DynamoDB supports in the attribute name

 
Screen Shot 2022-04-28 at 1 56 55 PM

## Motivation and Context

Fixes #3139.

## Testing

mvn clean install

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] I have added a changelog entry. Adding a new entry must be accomplished by running the `scripts/new-change` script and following the instructions. Commit the new file created by the script in `.changes/next-release` with your changes.
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

File: services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/EnhancedClientUtils.java [hunk 1]
```diff
@@ -47,15 +49,13 @@ private EnhancedClientUtils() {
      */
     public static String cleanAttributeName(String key) {
         boolean somethingChanged = false;
+        Set<Character> specialCharacters = Stream.of('*', '.', '-', '#', '+', ':', '/', '(', ')', '&', '<', '>',
+                                                     '?', '=', '!', '@', '%', '$', '|').collect(Collectors.toSet());
```
Comment (zoewangg) [inline services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/EnhancedClientUtils.java:53]: Can we make this local variable a constant?

**Review by zoewangg — APPROVED** [review]
