### PR TITLE
Fix stackoverflow with large pages in paginator

### LINKED ISSUE #6411: Hang (StackOverflow?) in ScanPublisher.items()
### Describe the bug

Using `DynamoDbAsyncClient`, when I try to scan a table with at least a few thousand elements and user the per-item publisher, the operation sometimes hangs.

Something like this: 
```
    client.scanPaginator(ScanRequest.builder()
        .tableName("test")
        .consistentRead(true)
        .build()).items().subscribe(_ -> counter.incrementAndGet()).join();
```
always hangs for me with the right size table (see repro repo). 

If I don't use `items()`, i.e. just inspect the individual pages, I never see a hang:
```
    client.scanPaginator(ScanRequest.builder()
        .tableName("test")
        .consistentRead(true)
        .build()).subscribe(response -> response.items().forEach(_ -> counter.incrementAndGet())).join();
```

I believe the issue is the recursive processing in [sendNextElement](https://github.com/aws/aws-sdk-java-v2/blob/59e3a000503e1299675698e5c4c7af51f2525669/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/pagination/async/ItemsSubscription.java#L86). If there are enough elements in a single page (in my repro, I could get 7K elements in a page which was enough), each element makes a recursive call to `sendNextElement` which probably blows out the stack. Nothing even listens on the `CompletionStage` returned by the `whenComplete` so this exception is silently dropped.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

The publisher should not hang and publish all elements of the scan

### Current Behavior

The publisher hangs forever

### Reproduction Steps

https://github.com/ravi-signal/scan-publisher-hang/tree/main is a fully self contained reproduction that has a [test](https://github.com/ravi-signal/scan-publisher-hang/blob/ae1461de53bccea12729d28ff0bf77deaaccc993/src/test/java/org/example/PageHangTest.java#L82) that always hangs for me. 

We noticed this in a production system pointed at a real dynamodb instance so I do not think this is a test artifact.

### Possible Solution

- Convert the recursive processing loop of the current page's results into an iterative one
- Surround the `whenComplete` in a try/catch and propagate exceptions to the subscriber

### Additional Information/Context

_No response_

### AWS Java SDK version used

2.33.5

### JDK version used

openjdk version "24.0.1" 2025-04-15 OpenJDK Runtime Environment Temurin-24.0.1+9 (build 24.0.1+9) OpenJDK 64-Bit Server VM Temurin-24.0.1+9 (build 24.0.1+9, mixed mode, sharing)

### Operating System and version

macOS 15.6.1

### PR DESCRIPTION
**Pull request by dagnir**
Previously, signalig onNext() to the subscriber was done via recursion, pulling elements from an iterator over the current page returned by the service. However, this can quickly lead to a stackoverflow error since the stack will grow linearly with the size of the page.

This commit fixes this issue by using SdkPublisher's builtin flatMapIterable(), which uses a loop to signal onNext(), and also ensures that it does not call itself recursively.

fixes #6411

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [ ] Local run of `mvn install` succeeds
- [ ] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed
- [ ] I have added a changelog entry. Adding a new entry must be accomplished by running the `scripts/new-change` script and following the instructions. Commit the new file created by the script in `.changes/next-release` with your changes.
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

File: core/sdk-core/src/test/java/utils/SdkSubscriberTest.java [hunk 1]
```diff
@@ -48,96 +47,83 @@ public class SdkSubscriberTest {
 
     public static final Function<Integer, Iterator<Integer>> SAMPLE_ITERATOR = response -> Arrays.asList(1, 2, 3, 4, 5, 6).listIterator();
     public static final Function<Integer, Iterator<Integer>> EMPTY_ITERATOR = response -> new ArrayList<Integer>().listIterator();
-    @Mock
-    AsyncPageFetcher asyncPageFetcher;
-    PaginatedItemsPublisher<Integer, Integer> itemsPublisher;
```
Comment (dagnir) [inline core/sdk-core/src/test/java/utils/SdkSubscriberTest.java:53]: Note: this test is just testing features of `SdkPublisher` such as `limit()`, not `PaginatedItemsPublisher` itself, so just removed this class entirely

File: codegen/src/main/java/software/amazon/awssdk/codegen/poet/paginators/AsyncResponseClassSpec.java [hunk 2]
```diff
@@ -200,21 +197,23 @@ private MethodSpec getMethodsSpecForSingleResultKey(String resultKey) {
...
-                                  ParameterizedTypeName.get(ClassName.get(Function.class),
-                                                            responseType(),
-                                                            ParameterizedTypeName.get(ClassName.get(Iterator.class),
-                                                                                      resultKeyType)))
-                         .addCode(getIteratorLambdaBlock(resultKey, resultKeyModel))
-                         .addCode("\n")
-                         .addStatement("return $1T.builder().$2L(new $3L()).iteratorFunction(getIterator).$4L($4L).build()",
-                                       PaginatedItemsPublisher.class, NEXT_PAGE_FETCHER_MEMBER, nextPageFetcherClassName(),
-                                       LAST_PAGE_FIELD)
+                         .addStatement("return this.flatMapIterable($L)", iterableFnBuilder.build())
```
Comment (alextwoods) [inline codegen/src/main/java/software/amazon/awssdk/codegen/poet/paginators/AsyncResponseClassSpec.java:216]: Nice!

File: test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/paginators/PaginatorsTest.java [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+        wireMock.stop();
+    }
+
+    @Test
+    @Timeout(value = 15, unit = TimeUnit.SECONDS)
+    void listStrings_largePage_succeeds() {
+        int nItems = 10_000;
+        wireMock.stubFor(post(urlEqualTo("/2016-03-11/listStrings"))
+                             .willReturn(aResponse().withStatus(200)
+                                                    .withJsonBody(createScanResponse(nItems))));
```
Comment (alextwoods) [inline test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/paginators/PaginatorsTest.java]: nit: slightly weird formatting

**Review by alextwoods — APPROVED** [review]

File: codegen/src/test/resources/software/amazon/awssdk/codegen/poet/paginators/PaginatedOperationWithResultKeyAndMoreResultsPublisher.java [hunk 4]
```diff
@@ -107,15 +103,7 @@ public void subscribe(Subscriber<? super PaginatedOperationWithResultKeyAndMoreR
      * and then applies that consumer to each response returned by the service.
      */
     public final SdkPublisher<SimpleStruct> items() {
-        Function<PaginatedOperationWithResultKeyAndMoreResultsResponse, Iterator<SimpleStruct>> getIterator = response -> {
-            if (response != null && response.items() != null) {
-                return response.items().iterator();
-            }
-            return Collections.emptyIterator();
-        };
-        return PaginatedItemsPublisher.builder()
```
Comment (zoewangg) [inline codegen/src/test/resources/software/amazon/awssdk/codegen/poet/paginators/PaginatedOperationWithResultKeyAndMoreResultsPublisher.java:116]: Should we deprecate `PaginatedItemsPublisher`?

**Review by zoewangg — APPROVED** [review]
