### PR TITLE
Handles the edge case in Netty client where HTTP/2 stream gets cleane…

### LINKED ISSUE #6561: NullPointerException while invoking the "writeHttp2RequestMetrics"
### Describe the bug

Race condition in AWS SDK 2.31.78 where HTTP/2 stream gets cleaned up before metrics collection completes, causing NPE in NettyRequestMetrics.writeHttp2RequestMetrics(). 

Please see the following stack trace for more details.

Stack Trace:
`java.lang.NullPointerException: Cannot invoke \"io.netty.handler.codec.http2.Http2Stream.getProperty(io.netty.handler.codec.http2.Http2Connection$PropertyKey)\" because \"stream\" is null
	at io.netty.handler.codec.http2.DefaultHttp2LocalFlowController.state(DefaultHttp2LocalFlowController.java:289)
	at io.netty.handler.codec.http2.DefaultHttp2LocalFlowController.windowSize(DefaultHttp2LocalFlowController.java:157)
	at software.amazon.awssdk.http.nio.netty.internal.NettyRequestMetrics.writeHttp2RequestMetrics(NettyRequestMetrics.java:82)
	at software.amazon.awssdk.http.nio.netty.internal.NettyRequestMetrics.lambda$publishHttp2StreamMetrics$0(NettyRequestMetrics.java:62)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at software.amazon.awssdk.http.nio.netty.internal.NettyRequestMetrics.publishHttp2StreamMetrics(NettyRequestMetrics.java:61)
	at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.lambda$writeRequest$13(NettyRequestExecutor.java:250)`

It appears that null-check for `stream` is needed in `NettyRequestMetrics.writeHttp2RequestMetrics()`

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

No NullPointerException

### Current Behavior

NullPointerException

### Reproduction Steps

The error occurred many times while making AWS Transcriber requests on Oct 25th  when recovering from the AWS east-1 outage.
It's hard to reproduce after then.

### Possible Solution

Adding the null-check for the `stream` 

private static void writeHttp2RequestMetrics(MetricCollector metricCollector,
                                             Channel channel,
                                             Http2Connection http2Connection) {
    int streamId = channel.attr(ChannelAttributeKey.HTTP2_FRAME_STREAM).get().id();

    Http2Stream stream = http2Connection.stream(streamId);
    if (stream != null) {
        metricCollector.reportMetric(Http2Metric.LOCAL_STREAM_WINDOW_SIZE_IN_BYTES,
                                     http2Connection.local().flowController().windowSize(stream));
        metricCollector.reportMetric(Http2Metric.REMOTE_STREAM_WINDOW_SIZE_IN_BYTES,
                                     http2Connection.remote().flowController().windowSize(stream));
    }
}

### Additional Information/Context

_No response_

### AWS Java SDK version used

2.31.78

### JDK version used

17

### Operating System and version

AWS EC2 c5.xlarge

### PR DESCRIPTION
**Pull request by zoewangg**
…d up before metrics collection completes, causing NPE to be thrown

## Motivation and Context
Fix #6561

Handles the edge case in Netty client where HTTP/2 stream gets cleaned up before metrics collection completes, causing NPE to be thrown

## Modifications
- Add stream null check
- Add try catch to handle all exceptions thrown from metrics collection and log a warn message if it fails instead of failing the request.

## Testing
Added unit tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [ ] Local run of `mvn install` succeeds
- [ ] My code follows the code style of this project
- [ ] My change requires a change to the Javadoc documentation
- [ ] I have updated the Javadoc documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed
- [ ] I have added a changelog entry. Adding a new entry must be accomplished by running the `scripts/new-change` script and following the instructions. Commit the new file created by the script in `.changes/next-release` with your changes.
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [ ] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

File: http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/Http2MetricsTest.java [hunk 1]
```diff
@@ -38,8 +38,10 @@
 import io.netty.util.ReferenceCountUtil;
 import java.net.URI;
 import org.junit.jupiter.api.AfterAll;
+import org.junit.jupiter.api.Assertions;
 import org.junit.jupiter.api.BeforeAll;
 import org.junit.jupiter.api.Test;
+import org.mockito.Mockito;
```
Comment (dagnir) [inline http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/Http2MetricsTest.java]: Nit: are these imports necessary? Doesn't look like they get used in this diff

**Review by dagnir — APPROVED** [review]
