### PR TITLE
Fix bug in using nonProxyHosts with CRT http/s3 clients

### LINKED ISSUE #6414: S3AsyncClient CRT Client does not honor S3CrtProxyConfiguration - nonProxyHosts is not being read
### Describe the bug

Hi @debora-ito   I am also running into this issue: https://github.com/aws/aws-sdk-java-v2/issues/5179
I am using 0.38.11 version of https://mvnrepository.com/artifact/software.amazon.awssdk.crt/aws-crt
In my test I am setting the following properties:

```
System.setProperty("https.proxyHost", "proxy.example.com");
System.setProperty("https.proxyPort", "8080");
System.setProperty("http.nonProxyHosts", "127.0.0.1");
System.setProperty("aws.crt.log.level","Trace");
System.setProperty("aws.crt.log.destination","Stdout");
```

Proxy.example.com is an invalid proxy so the resolution will fail if the client tries to use it. For nonProxyHosts, it is 127.0.0.1 where I have running a LocalStack instance.

Then I create the S3AsyncClient and a TransferManager client with it to use, for example, a download directory operation:

```
S3AsyncClient s3Async =
        S3AsyncClient.crtBuilder()
            .endpointOverride(localstack.getEndpoint())
            .credentialsProvider(
                StaticCredentialsProvider.create(
                    AwsBasicCredentials.create(
                        localstack.getAccessKey(), localstack.getSecretKey())))
            .region(Region.of(localstack.getRegion()))
            .responseChecksumValidation(ResponseChecksumValidation.WHEN_REQUIRED)
            .requestChecksumCalculation(RequestChecksumCalculation.WHEN_REQUIRED)
            .httpConfiguration(S3CrtHttpConfiguration.builder()
                .proxyConfiguration(AwsCloudStorageUtils.getProxyConfiguration())
                .build())
            .build();

    S3TransferManager transferManager = S3TransferManager.builder()
        .s3Client(s3Async)
        .build();
```

```
public static S3CrtProxyConfiguration getProxyConfiguration() {
    String proxyHost = System.getProperty("https.proxyHost");

    if (StringUtils.isEmpty(proxyHost)) {
      return null;
    }

    String proxyPortStr = System.getProperty("https.proxyPort");
    int proxyPort = 8080;

    if (!StringUtils.isEmpty(proxyPortStr)) {
      try {
        proxyPort = Integer.parseInt(proxyPortStr.trim());
      } catch (NumberFormatException e) {
        proxyPort = 8080;
      }
    }

    return (S3CrtProxyConfiguration) S3CrtProxyConfiguration.builder()
        .host(proxyHost.trim())
        .port(proxyPort)
        .nonProxyHosts(getNonProxyHosts())
        .build();
  }

 
  public static Set<String> getNonProxyHosts() {
    Set<String> result = new HashSet<>();

    String nonProxyHosts = System.getProperty("http.nonProxyHosts");
    if (StringUtils.isEmpty(nonProxyHosts)) {
      return result;
    }

    String[] hosts = nonProxyHosts.split("\\|");
    for (String host : hosts) {
      String trimmedHost = host.trim();
      result.add(trimmedHost);
    }

    return result;
  }
```

Then I store two files in a "directory" called `test-files/` , with a non-Crt S3 Client. Then I try do download them with the Crt client above.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Connect to my Localstack instance on 127.0.0.1 without any attempt to go through the invalid proxy "proxy.example.com"

### Current Behavior

The connection is taking place through a tunnel via proxy:

CRT Trace logs:
**(STATIC) Connecting to "127.0.0.1" through a tunnel via proxy "proxy.example.com"**

```
GET
/proxy-test-bucket
list-type=2&prefix=test-files%2F
amz-sdk-invocation-id:7301f957-1a92-d83c-0197-4807a4b77820
amz-sdk-request:attempt=1; max=1
content-length:0
host:127.0.0.1:59919
x-amz-content-sha256:UNSIGNED-PAYLOAD
x-amz-date:20250910T103030Z
...
[INFO] [2025-09-10T10:30:30Z] [0000000173ac3000] [connection-manager] - id=0x114053390: Requesting 1 new connections from http
[INFO] [2025-09-10T10:30:30Z] [0000000173ac3000] [http-connection] - (STATIC) Connecting to "127.0.0.1" through a tunnel via proxy "proxy.example.com"
[DEBUG] [2025-09-10T10:30:30Z] [0000000173ac3000] [channel-bootstrap] - id=0x600002a02ed0: acquiring bootstrap reference
[TRACE] [2025-09-10T10:30:30Z] [0000000173ac3000] [http-connection] - static: attempting to initialize a new client channel to proxy.example.com:8080
[TRACE] [2025-09-10T10:30:30Z] [0000000173ac3000] [channel-bootstrap] - id=0x600002a02ed0: attempting to initialize a new client channel to proxy.example.com:8080
[DEBUG] [2025-09-10T10:30:30Z] [0000000173ac3000] [channel-bootstrap] - id=0x600002a02ed0: acquiring bootstrap reference
[DEBUG] [2025-09-10T10:30:30Z] [0000000173ac3000] [dns] - id=0x6000036f9080: Host resolution requested for proxy.example.com
[DEBUG] [2025-09-10T10:30:30Z] [0000000173ac3000] [dns] - id=0x6000036f9080: No cached entries found for proxy.example.com starting new resolver thread.
[TRACE] [2025-09-10T10:30:30Z] [0000000173ac3000] [standard-retry-strategy] - id=0x600002f21080: on_retry_token_acquired callback completed
[TRACE] [2025-09-10T10:30:30Z] [0000000173ac3000] [event-loop] - id=0x60000210d040: no more scheduled tasks using default timeout.
[TRACE] [2025-09-10T10:30:30Z] [0000000173ac3000] [event-loop] - id=0x60000210d040: waiting for a maximum of 100s 0ns
[DEBUG] [2025-09-10T10:30:30Z] [0000000174b77000] [dns] - static: resolving host proxy.example.com
[ERROR] [2025-09-10T10:30:30Z] [0000000174b77000] [dns] - static: getaddrinfo failed with error_code 8: nodename nor servname provided, or not known
[WARN] [2025-09-10T10:30:30Z] [0000000174b77000] [dns] - static, resolving host proxy.example.com failed, ec 1059 (aws-c-io: AWS_IO_DNS_INVALID_NAME, Host name was invalid for dns resolution.)
```

### Reproduction Steps

Use the following values for these properties:
```
System.setProperty("https.proxyHost", "proxy.example.com");
System.setProperty("https.proxyPort", "8080");
System.setProperty("http.nonProxyHosts", "127.0.0.1");
System.setProperty("aws.crt.log.level","Trace");
System.setProperty("aws.crt.log.destination","Stdout");
```
 
1. Create a LocalStack sandbox for testing
```
@Container
  public static LocalStackContainer localstack =
      new LocalStackContainer(DockerImageName.parse("localstack/localstack:0.11.3"))
          .withServices(S3);
```

 
2. Create S3Client (not async), S3AsyncClient (Crt) and a TransferManager client based on the async s3 client:

```
        S3Client s3 = S3Client.builder()
            .endpointOverride(localstack.getEndpoint())
            .credentialsProvider(
                StaticCredentialsProvider.create(
                    AwsBasicCredentials.create(
                        localstack.getAccessKey(), localstack.getSecretKey())))
            .region(Region.of(localstack.getRegion()))
            .responseChecksumValidation(ResponseChecksumValidation.WHEN_REQUIRED)
            .requestChecksumCalculation(RequestChecksumCalculation.WHEN_REQUIRED)
            .build();

    S3AsyncClient s3Async =
        S3AsyncClient.crtBuilder()
            .endpointOverride(localstack.getEndpoint())
            .credentialsProvider(
                StaticCredentialsProvider.create(
                    AwsBasicCredentials.create(
                        localstack.getAccessKey(), localstack.getSecretKey())))
            .region(Region.of(localstack.getRegion()))
            .responseChecksumValidation(ResponseChecksumValidation.WHEN_REQUIRED)
            .requestChecksumCalculation(RequestChecksumCalculation.WHEN_REQUIRED)
            .httpConfiguration(S3CrtHttpConfiguration.builder()
                .proxyConfiguration(AwsCloudStorageUtils.getProxyConfiguration())
                .build())
            .build();

    S3TransferManager transferManager = S3TransferManager.builder()
        .s3Client(s3Async)
        .build();
```

This is the configuration I am using:

```
public static S3CrtProxyConfiguration getProxyConfiguration() {
    String proxyHost = System.getProperty("https.proxyHost");

    if (StringUtils.isEmpty(proxyHost)) {
      return null;
    }

    String proxyPortStr = System.getProperty("https.proxyPort");
    int proxyPort = 8080;

    if (!StringUtils.isEmpty(proxyPortStr)) {
      try {
        proxyPort = Integer.parseInt(proxyPortStr.trim());
      } catch (NumberFormatException e) {
        proxyPort = 8080;
      }
    }

    return (S3CrtProxyConfiguration) S3CrtProxyConfiguration.builder()
        .host(proxyHost.trim())
        .port(proxyPort)
        .nonProxyHosts(getNonProxyHosts())
        .build();
  }


  public static Set<String> getNonProxyHosts() {
    Set<String> result = new HashSet<>();

    String nonProxyHosts = System.getProperty("http.nonProxyHosts");
    if (StringUtils.isEmpty(nonProxyHosts)) {
      return result;
    }

    String[] hosts = nonProxyHosts.split("\\|");
    for (String host : hosts) {
      String trimmedHost = host.trim();
      result.add(trimmedHost);
    }

    return result;
  }
```

3. Create buckets, upload files... using the S3Client (not async)
4. Try to download a directory (for example) with the AsyncS3Client via TransferManager

### Possible Solution

N/A

### Additional Information/Context

Using version 0.38.11 aws crt https://mvnrepository.com/artifact/software.amazon.awssdk.crt/aws-crt/0.38.11

### AWS Java SDK version used

2.32.31

### JDK version used

java version "21.0.1" 2023-10-17 LTS

### Operating System and version

MacOS 15.6.1

### PR DESCRIPTION
**Pull request by alextwoods**
Fix bug in using nonProxyHosts with CRT http/s3 clients.

Fixes #6414

## Motivation and Context
#4974 added the `nonProxyHosts` configuration to the `CrtProxyConfiguration` used by the CRT HTTP Client and S3 Client.  However, the implementation had a bug and was [checking the nonProxyHosts against the proxy host](https://github.com/aws/aws-sdk-java-v2/blob/f525dfd6cffbce1bd005f4bc37156ad71a129a3a/core/crt-core/src/main/java/software/amazon/awssdk/crtcore/CrtConfigurationUtils.java#L40) instead of against the request's endpoint.

Checking against the request's endpoint is tricky and for the S3 Client, not possible, since the endpoint is resolved per request.  Rather than implementing the no proxy hosts logic in Java, this PR uses the `noProxyHosts` CRT configuration.

There is a difference in the format/support for no proxy hosts configuration between CRT and pure Java (apache/netty clients):  the Java implementation allows arbitrary regex but does not support CIDR style ip addresses.  CRT's implementation follows the format used by curl and the only wild card supported is a single "*". It also supports CIDR style ip addresses.  

These differences exist today in the use of no proxy environment/system properties.  

Despite this behavior difference, this PR is NOT a breaking change since the nonProxyHosts configuration was not actually being applied before.  

## Modifications
* Update to latest aws-crt dependency (which includes the [noProxyHosts binding](https://github.com/awslabs/aws-crt-java/pull/925))
* Set the `noProxyHosts` on CRT's `HttpProxyOptions`, allowing it to be used by CRT.

## Testing
Modified existing tests + manual testing of crt http client and s3 client.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [x] My change requires a change to the Javadoc documentation
- [x] I have updated the Javadoc documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] I have added a changelog entry. Adding a new entry must be accomplished by running the `scripts/new-change` script and following the instructions. Commit the new file created by the script in `.changes/next-release` with your changes.
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

File: core/crt-core/src/main/java/software/amazon/awssdk/crtcore/CrtConfigurationUtils.java [hunk 1]
```diff
@@ -37,13 +33,14 @@ public static Optional<HttpProxyOptions> resolveProxy(CrtProxyConfiguration prox
...
         }
-        if (doesTargetMatchNonProxyHosts(proxyConfiguration.host(), proxyConfiguration.nonProxyHosts())) {
-            return Optional.empty();
-        }
+
         HttpProxyOptions clientProxyOptions = new HttpProxyOptions();
 
         clientProxyOptions.setHost(proxyConfiguration.host());
         clientProxyOptions.setPort(proxyConfiguration.port());
+        if (!proxyConfiguration.nonProxyHosts().isEmpty()) {
```
Comment (S-Saranya1) [inline core/crt-core/src/main/java/software/amazon/awssdk/crtcore/CrtConfigurationUtils.java:41]: Can this be null? Should we add a null safety check for proxyConfiguration.nonProxyHosts() before calling isEmpty() ?

File: core/crt-core/src/main/java/software/amazon/awssdk/crtcore/CrtConfigurationUtils.java [hunk 2]
```diff
@@ -37,13 +33,14 @@ public static Optional<HttpProxyOptions> resolveProxy(CrtProxyConfiguration prox
         if (proxyConfiguration == null) {
             return Optional.empty();
         }
-        if (doesTargetMatchNonProxyHosts(proxyConfiguration.host(), proxyConfiguration.nonProxyHosts())) {
```
Comment (S-Saranya1) [inline core/crt-core/src/main/java/software/amazon/awssdk/crtcore/CrtConfigurationUtils.java:40]: Question: This removed `doesTargetMatchNonProxyHosts` method had logic to check if the target matches non-proxy hosts before creating proxy options. So, CRT will handle all this proxy bypass logic correct?

**Comment by L-Applin** [comment]
My only concern is that if users were setting non-proxy hosts before and it had no effect, this PR would enable non-proxy-host and could bypass the proxy for some requests that weren't bypassing it previously, correct?

File: core/crt-core/src/main/java/software/amazon/awssdk/crtcore/CrtConfigurationUtils.java (hunk 2 above)
Comment (alextwoods) [reply core/crt-core/src/main/java/software/amazon/awssdk/crtcore/CrtConfigurationUtils.java:40]: Yup, exactly! 

CRT needs to handle applying the setting since endpoint is determined per request - so with the s3 client for example, we can't know whether to apply/skip the proxy up front.

File: core/crt-core/src/main/java/software/amazon/awssdk/crtcore/CrtConfigurationUtils.java (hunk 1 above)
Comment (alextwoods) [reply core/crt-core/src/main/java/software/amazon/awssdk/crtcore/CrtConfigurationUtils.java:41]: I actually had a null check in here originally, but spotbugs flagged it. 

The `nonProxyHosts` getter method ensures it is never null, see: https://github.com/aws/aws-sdk-java-v2/blob/740d5ac4f0ebee3ea722bbf5767fab6c791aeced/core/crt-core/src/main/java/software/amazon/awssdk/crtcore/CrtProxyConfiguration.java#L154

**Comment by alextwoods** [comment]
> My only concern is that if users were setting non-proxy hosts before and it had no effect, this PR would enable non-proxy-host and could bypass the proxy for some requests that weren't bypassing it previously, correct?

Yeah - this is true and I think a fair concern, but I think I'd consider it a reasonable break fix - if a user has explicitly configured a non-proxy-host we should use it.   Existing system/environment uses of nonProxyHost should remain unchanged, so its only explicit in code configurations that should now start working.

We could mitigate that risk by introducing a new configuration (`nonProxyHost_butThisTimeIMeanIt`) and deprecating the old one, but I think I'd argue that this is a reasonable fix of existing broken behavior.

**Comment by L-Applin** [comment]
> > My only concern is that if users were setting non-proxy hosts before and it had no effect, this PR would enable non-proxy-host and could bypass the proxy for some requests that weren't bypassing it previously, correct?
> 
> Yeah - this is true and I think a fair concern, but I think I'd consider it a reasonable break fix - if a user has explicitly configured a non-proxy-host we should use it. Existing system/environment uses of nonProxyHost should remain unchanged, so its only explicit in code configurations that should now start working.
> 
> We could mitigate that risk by introducing a new configuration (`nonProxyHost_butThisTimeIMeanIt`) and deprecating the old one, but I think I'd argue that this is a reasonable fix of existing broken behavior.

Yeah, I agree that `if a user has explicitly configured a non-proxy-host we should use it`. I'm just thinking of the situation where user would have set a non-proxy-host for a dev/local setup environment, but then inadvertently leaked that same config to their prod environment (unknowingly because it didn't take effect previously). I don't know how much of a concern that would be, it does seems unlikely.
