### PR TITLE
Bypass SSL validation when TRUST_ALL_CERTIFICATES is set to true

### LINKED ISSUE #1163: UrlConnectionHttpClient doesn't honor TRUST_ALL_CERTIFICATES
## Expected Behavior
When setting `TRUST_ALL_CERTIFICATES` to true, using `UrlConnectionHttpClient` should work for local https server

## Current Behavior
Exception thrown
```
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

## Steps to Reproduce (for bugs)
Using UrlConnectionHttpClient to send request to local https server

## Your Environment

* AWS Java SDK version used:  N/A
* JDK version used: N/A
* Operating System and version: N/A

### PR DESCRIPTION
**Pull request by zoewangg**
## Description
Bypass SSL validation when `TRUST_ALL_CERTIFICATES` is set to true in `UrlConnectionHttpClient`

## Motivation and Context
fix #1163 

## Testing
Added unit tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [x] Local run of `mvn install` succeeds
- [x] My code follows the code style of this project
- [x] My change requires a change to the Javadoc documentation
- [x] I have updated the Javadoc documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] A short description of the change has been added to the **CHANGELOG**
- [ ] My change is to implement 1.11 parity feature and I have updated [LaunchChangelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

File: http-clients/url-connection-client/src/test/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClientWireMockTest.java [hunk 1]
```diff
@@ -14,12 +14,37 @@
...
         return UrlConnectionHttpClient.create();
     }
+
+    @After
+    public void reset() {
+        HttpsURLConnection.setDefaultSSLSocketFactory((SSLSocketFactory) SSLSocketFactory.getDefault());
+    }
+
+    @Test
+    public void trustAllCertificates_shouldWork() throws Exception {
```
Comment (varunnvs92) [inline http-clients/url-connection-client/src/test/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClientWireMockTest.java]: Can you add a test that fails when TRUST_ALL_CERTIFICATES is false.

Comment (zoewangg) [reply http-clients/url-connection-client/src/test/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClientWireMockTest.java]: We already have one :)  

https://github.com/aws/aws-sdk-java-v2/blob/master/test/http-client-tests/src/main/java/software/amazon/awssdk/http/SdkHttpClientTestSuite.java#L99
